### ISSUE TITLE
d-feet cannot find Python3

### ISSUE THREAD

**Issue by ousia** [msys2/MINGW-packages#10248]
Hi there,

I have installed `mingw-w64-x86_64-d-feet` and when I try to invoke it, I get the following error message:

```
$ d-feet
-bash: /mingw64/bin/d-feet: D:\a\_temp\msys\msys64\mingw64\bin/python3.EXE: bad interpreter: No such file or directory
```

I don’t know whether the `EXE` uppercase extension might be causing this.

Many thanks for your excellent work.

**Comment by Biswa96** [comment]
Thank you for reporting this issue. I have created a pull request to fix the issue. If you want you can test the packages from GitHub Actions artifacts in the linked pull request.

This issue is part of this bigger one https://github.com/msys2/MINGW-packages/issues/7481. Sometime the CI build path got appended in the python shebang. We are fixing this type of issues gradually.

**Comment by ousia** [comment]
@Biswa96, many thanks for fixing the issue and updating the package.

@lazka, many thanks for merging the pull request.
