### ISSUE TITLE
Inconsistent set of macros defined for Minw64 under -std

### ISSUE THREAD

**Issue by yugr** [msys2/MINGW-packages#10406]
Mingw64 gcc does not define `WIN32` macro for C++ files if `-std` option is used (C files are ok):
```
$ gcc -E -dM -x c++ /dev/null 2>&1 | grep '\<WIN32\>'
1
$ gcc -E -dM -x c /dev/null -std=c++98 2>&1 | grep '\<WIN32\>'
1
$ gcc -E -dM -x c++ /dev/null -std=c++98 2>&1 | grep -c '\<WIN32\>'
0
$ gcc -E -dM -x c++ /dev/null -std=c++11 2>&1 | grep -c '\<WIN32\>'
0
$ gcc -E -dM -x c++ /dev/null -std=c++14 2>&1 | grep -c '\<WIN32\>'
0
```
I think for consistency `WIN32` should be defined in all cases (like `_WIN32` is).

**Comment by 1480c1** [comment]
I think I would prefer it to not be defined by the compiler at all if possible since it has no decorator like an `_` and I've often seen project define their own `WIN32` macro along with their own `MACOS` and `LINUX` macros and that could cause an issue of redefining and collisions, and https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170 only specifies the single `_` decorated macro, and the only cases in which I could get a undecorated `WIN32` was in the cases where I used the gnu versions of the standards instead of the standard C and C++ versions and the weird case of using gcc with c input but c++ standard.

**Comment by 1480c1** [comment]
Btw, a similar thing occurs on linux as well with gcc not defining `linux` if it's not one of the gnu extension standards or the c input but with c++ standard

**Comment by yugr** [comment]
Ah, makes sense, so this non-standard macro is defined only for GNU standards like `-std=gnu++98`.
