### ISSUE TITLE
Python 3.10 Update/Transition

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#10515]
Note: Unrelated package updates are currently paused to focus on the Python rebuilds.

Just an issue to collect things for when the time comes.

* [x] https://github.com/msys2-contrib/cpython-mingw/issues/52
* [x] Some packages are missing .pyc files. We should look for them, and if they are versioned we can manually compile them without breaking updates. Example: https://github.com/msys2/MINGW-packages/pull/10475, python-jsonschema
* [x] rebase .pyc PRs and merge them
* [x] Rebuild everything
* [x] disable bootstrap for wheel/tomli, rebuild clang

**Comment by MehdiChinoune** [comment]
Last year, Upgrading to Python 3.9 was delayed until June-2021 because of the huge job of rebasing patches and testing.
Then a new repository - https://github.com/msys2-contrib/cpython-mingw - was created to not make it happen again (That's my understanding).
Was that goal achieved? I don't think so.
I think that was because of the approach chosen, waiting until final release and rebase/chery-pick patches. That work should started with alpha release.
For example with Qt6 I start test packaging it with beta releases.
The same apply to other essential/huge projects like LLVM, GCC. We should start testing them with beta releases (Maybe even better by forking them and setup a scheduled-GHA to rebase our patches)

**Comment by lazka** [comment]
Packages missing bytecode files:

```
mingw-w64-adios2
mingw-w64-d-feet
mingw-w64-gedit
mingw-w64-geographiclib
mingw-w64-gexiv2
mingw-w64-gitg
mingw-w64-graphviz
mingw-w64-gst-editing-services
mingw-w64-gst-python
mingw-w64-kicad
mingw-w64-libbotan
mingw-w64-libcaca
mingw-w64-libftdi
mingw-w64-libgit2-glib
mingw-w64-libproxy
mingw-w64-libsbml
mingw-w64-libvoikko
mingw-w64-libxml2
mingw-w64-mlt
mingw-w64-nlopt
mingw-w64-openturns
mingw-w64-partio
mingw-w64-plplot
mingw-w64-pyside2-qt5
mingw-w64-pyside6
mingw-w64-python-entrypoints
mingw-w64-pygobject
mingw-w64-python-ipykernel
mingw-w64-python-ipython
mingw-w64-python-jsonschema
mingw-w64-python-jupyter_client
mingw-w64-python-jupyter_core
mingw-w64-python-maturin
mingw-w64-python-mistune
mingw-w64-bullet
mingw-w64-python-pyzmq
mingw-w64-python-qtconsole
mingw-w64-sip4
mingw-w64-python-testpath
mingw-w64-shiboken2-qt5
mingw-w64-shiboken6
mingw-w64-tulip
mingw-w64-vigra
mingw-w64-volk
mingw-w64-wxPython
mingw-w64-wxPython4.0
mingw-w64-z3
```

**Comment by lazka** [comment]
There are many more packages missing .pyc files, and they are not all fun to build.. so I think I'll leave it what I have now.

**Comment by mmuetzel** [comment]
Should the ARM builder also start building this for staging?
It'll probably need some hints to break dependency cycles.

**Comment by lazka** [comment]
@jeremyd2019 for breaking cycles: `mingw-w64-python:mingw-w64-libxml2,mingw-w64-python-fixtures:mingw-w64-python-testtools,mingw-w64-opencolorio:mingw-w64-openimageio,mingw-w64-vtk:mingw-w64-opencv,mingw-w64-python-sphinx:mingw-w64-python-pygments`

**Comment by mmuetzel** [comment]
What are the remaining steps for this? Set tomli back to non-bootstrapping mode? Anything else?

**Comment by lazka** [comment]
all done now.

**Comment by lazka** [comment]
If there is any fallout feel free to ping me.

**Comment by lazka** [comment]
@mmuetzel thanks for fixing all those packages :)

**Comment by mmuetzel** [comment]
No worries. That was a nice opportunity to learn something about a couple of build systems.
