### ISSUE TITLE
Incompatible typedef of `HRESULT` with clang

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#10618]
Trying to re-compile ffmpeg with CLANG32 currently fails with the following error (see also #9931):
```
 In file included from C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.1/libavcodec/amfenc.c:35:
  In file included from C:/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.1/libavcodec/amfenc.h:22:
  In file included from D:/M/msys64/clang32/include/AMF/core/Factory.h:37:
  D:/M/msys64/clang32/include/AMF/core/Platform.h:76:20: error: typedef redefinition with different types ('int' vs 'LONG' (aka 'long'))
  typedef signed int HRESULT;
                     ^
  D:/M/msys64/clang32/i686-w64-mingw32/include/winnt.h:419:16: note: previous definition is here
  CC	libavcodec/amfenc_h264.o
    typedef LONG HRESULT;
                 ^
  1 error generated.
  make: *** [/C/_/mingw-w64-ffmpeg/src/ffmpeg-4.4.1/ffbuild/common.mak:67: libavcodec/amfenc.o] Error 1
  make: *** Waiting for unfinished jobs....
```

IIUC, the conflicting headers are both installed by MSYS2/CLANG32. 

Same error with CLANG64.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request? The test packages can be downloaded from here https://github.com/msys2/MINGW-packages/actions/runs/1756330287

The fix for this issue has been reported to upstream here https://github.com/GPUOpen-LibrariesAndSDKs/AMF/pull/286. Thank you @1480c1.

**Comment by mmuetzel** [comment]
Thank you @Biswa96. That fixes the error for me. Tested with CLANG64 after installing the artifact from your PR.
