### ISSUE TITLE
Current runner OS has missing windows header files.

### ISSUE THREAD

**Issue by BFamzz** [msys2/MINGW-packages#10690]
The current virtual environment ("windows-2022") that runs job is not suitable for desktop development (WinRT, Win32 amongst others) as stated Microsoft's [release notes](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/). 

An excerpt from the [homepage ](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/) notification banner "_Windows 10, version 21H2 is a scoped set of features for select performance improvements and quality enhancements. Developers should be aware of this release, but no action is necessary at this time._"

Further discussion [here](https://docs.microsoft.com/en-us/answers/questions/416487/regarding-34this-release-20348-doesn39t-introduce.html)

<img width="334" alt="image" src="https://user-images.githubusercontent.com/38426051/152714789-99e43073-3949-44fd-ac53-e317eedc2fe8.png">

The latest [release](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/) is not yet available on Github. Pending while it is available, is there a way to revert back to the previous version "windows-2019"  as some windows header files are missing from "windows-2022" and causing builds to fail?

Thanks.

Edit: I think it is related to this ros-tooling/action-ros-ci#719 and actions/virtual-environments#5027

**Comment by jeremyd2019** [comment]
I think you are conflating Windows OS version and Windows SDK version.  The Server 2022 SDK may not be suitable for desktop development.

As far as this repo is concerned, it uses mingw-w64 headers and libraries, not the Windows SDK ones.

Also, those issues you linked to are due to an issue in pip (technically the simple launcher, which is vendored into pip by way of distlib), not anything to do with Windows or mingw-w64.

**Comment by BFamzz** [comment]
Alright. Thanks for the clarification. Closing the issue now.
