### ISSUE TITLE
mingw-w64-git

### ISSUE THREAD

**Issue by 89z** [msys2/MINGW-packages#10749]
I am not seeing this package:

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-git

and it seems to be available in other places

**Comment by 89z** [comment]
Not `mingw-w64`, `mingw-w64-git`. That would be a Windows native build of Git, one that doesnt rely on MSYS2 DLL.

**Comment by Biswa96** [comment]
@dscho provided some details here https://www.youtube.com/watch?v=tamENApCvs0

**Comment by 89z** [comment]
Yes, I have always wondered why a native Windows version was not available. I even built my own a while back, but it was a lot of trouble. Yes, some Git stuff is still as shell scripts (notably Git bisect), but a good chunk of the core features are in C.

**Comment by 89z** [comment]
Huh, it seems the native Windows Git is available as "MinGit". It also seems that its been available going back even to 2016:

https://github.com/git-for-windows/git/releases/tag/v2.9.0.windows.1

Am I understanding that correctly? Is there something "wrong" with the native Windows Git? I just feel like Ive been living under a rock here, as I have wanted that for years, and its already been around?

**Comment by dscho** [comment]
@89z let's clarify a few things because I sense tremendous confusion:

* MSYS2 is a software distribution and building platform for Windows
* MSYS2 comes in the form of Pacman packages
* You can install and remove Pacman packages as needed
* `mingw-w64-git` is the name of one of the packages in MSYS2
* Git for Windows is a stand-alone product, based on MSYS2, with a few specific modifications to make Git run better
* Git for Windows bundles a fixed set of files from a fixed set of Pacman packages into a regular installer
* MinGit is a minimal subset of Git for Windows _intended for applications_

So, saying "it seems the native Windows Git is available as MinGit" is kind of completely missing the point ;-)

MinGit is _not_ a Pacman package. It does not integrate into MSYS2. To the contrary, it is a _subset_ of a snapshot of a slightly modified MSYS2 installation.

Another part of your confusion probably stems from the fact that `mingw-w64-git` is not the name of what `pacman -Q` lists, as the CPU architecture is used as an infix. Meaning: in a x86_64 MSYS2, you might have `mingw-w64-x86_64-git`, in an i686 setup you would have `mingw-w64-i686-git`. The overall package name still is `mingw-w64-git`.

**Comment by 89z** [comment]
@dscho thanks for the comment, but I think you've introduced some facts that stray from what I am looking for. With MSYS2, some packages will be the `msys` variant, which rely on the MSYS2 DLL:

https://packages.msys2.org/base/openssl

and then in some cases, you will have the same package as the `mingw` variant, which will not rely on the MSYS2 DLL:

https://packages.msys2.org/base/mingw-w64-openssl

what I want, is the `mingw` variant for Git. So as I said before, a Windows native version of Git. Since its not currently available via MSYS2 (via official mirrors), I am fine with using it via MinGit. I don't care if MinGit is MSYS2, I only care that the Git is native Windows.

**Comment by dscho** [comment]
@89z you contradict yourself. On the one hand you ask for `mingw-w64-git`, i.e. a package that integrates well into MSYS2. On the other hand you claim that you're using MinGit _which does not integrate well with MSYS2 because it brings its own MSYS2 runtime_.

Also, you seem to care really little about what else I said, namely that MinGit is intended for applications, not for interactive use. Since you seem to happy to ignore what I say, I will save my breath and just ignore this ticket henceforth.

**Comment by 89z** [comment]
@dscho I'm not sure how many times I need to say it. I want a Windows native Git. In the context of MSYS2, that would be mingw-w64-git. In the context of "Git for Windows", that would be MinGit. I don't care who the provider is, as long as it's native Windows. Why are you not understanding this?

**Comment by 89z** [comment]
I want a Windows native Git. In the context of MSYS2, that would be `mingw-w64-git`. However if another option is available (such as MinGit), then I am fine with that too.

**Comment by elieux** [comment]
I'll try to answer directly to what *I think* you're asking for. If I'm mistaken, I apologize.

We have an _msys/git_ package, but you don't want that one. We have a recipe for the _mingw-w64-git_ packages in this repository, but since these packages don't work well out of the box, we don't build them. Thankfully, there's Git for Windows, which is a software distribution with the main content being a mingw-w64 Git. This is exactly what you want. I'd like to note that the main, user-centric variant there is Git-2.35.1.2-64-bit.exe, not MinGit. Coincidentally though, Git for Windows is somewhat compatible with MSYS2 and there is a way to combine those two, described here: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

I'm closing this issue because although we'd like to have a mingw-w64 Git someday, keeping an open issue about it doesn't really help. The discussion can continue.

**Comment by 89z** [comment]
@elieux in many projects I have worked on, closing an issue sends the message of "wont fix". If you wish to define closure as something else, its your right to do so. However you should know, that regardless of any comment you've made here to clarify your intentions, that many people seeing the closed issue will interpret that as such. In general I have found closed issues rarely get fixed, because the maintainers simply forget about them.
