### ISSUE TITLE
Packages silently fail if dependencies are out of date

### ISSUE THREAD

**Issue by jdpipe** [msys2/MINGW-packages#10752]
I have installed mingw-w64-x86_64-innoextract 1.9-3, and attempt to run it. On my system, I get a silent fail, like this:

![image](https://user-images.githubusercontent.com/87423/153964431-e927a939-3790-4677-b6bc-7944ea06c52c.png)

I opened innoextract.exe using the Dependency Walker and it flags an issue with the linking to libboost_filesystem-mt.dll:

![image](https://user-images.githubusercontent.com/87423/153964516-a4675d91-d56b-405e-bef8-76d5374278c4.png)

I didn't get any errors when I installed `innoextract`, however just now, running `pacman -Syuu` I discovered that there is a new Boost release.

Shouldn't pacman or MSYS2 itself be smart enough to tell me when I am installing a package with out of date dependencies? Do binary packages get associated in the database with the specific version of a library that they require, or is this something that needs to be added one day? Should bash do a bit more to report error codes from binaries that fail to run due to linking/loading issues, alternatively?

**Comment by Biswa96** [comment]
Thank you for reporting the issue. This happens sometime when dependencies are changed. Generally, dependent packages are re-built manually at that time.

**Comment by jeremyd2019** [comment]
As far as the (lack of) errors, that's an issue.  If you set MSYS=winjitdebug before starting the shell, the Windows error dialogs will not be suppressed.  They are suppressed by default because having Windows wait on showing an error dialog is very problematic on things like CI systems where there is no interactive user to see them.  There is supposed to be an error shown by Cygwin, I know it is shown for a missing DLL, but it is known to lie about what DLL is having the problem.

As far as that symbol being a problem in libboost_filesystem-mt.dll, here are the packages that reference that symbol (that need rebuilds as @Biswa96 said:
* mingw-w64-openimageio
* mingw-w64-innoextract
* mingw-w64-collada-dom-svn
* mingw-w64-precice

**Comment by jeremyd2019** [comment]
jeremyd2019/package-grokker#9

**Comment by jdpipe** [comment]
I used the PKGBUILD to build this package on my local system, it now builds and runs fine.

Would be great to see the MSYS2 support tools catching these rebuilds automatically somehow. I note that the PKGBUILD 'check()' function could be used to provide some automated checking of previously-built packages, as an alternative.

But mostly, I'm surprised that changes to 'boost' didn't trigger an automatic rebuild of this package...???

**Comment by jeremyd2019** [comment]
I made a script, and confirmed that collada-dom-svn is the only remaining package that refers to symbols removed between boost 1.77.0-3 and 1.78.0-3 (assuming my script works properly!).
