### ISSUE TITLE
Run-time Qt version 5.15.3 does not match compile-time Qt version 5.15.2

### ISSUE THREAD

**Issue by RoslynHenry** [msys2/MINGW-packages#10952]
I'm trying to run an app on windows (slimGUI.exe, mingw-w64-x86_64-slim-simulator) and Qt is one of the dependancies. I followed the same download protocol today as I have on previous machines but now with this download when I try to run the gui I get the following message on the console,

"Run-time Qt version 5.15.3 does not match compile-time Qt version 5.15.2"

Is it possible for the Qt version on Msys2 to be updated to version 5.15.3?

**Comment by MehdiChinoune** [comment]
> "Run-time Qt version 5.15.3 does not match compile-time Qt version 5.15.2"

slim-simulator was built against Qt 5.15.2 (compile-time), while Qt has been updated to 5.15.3 (Run-time).
> Is it possible for the Qt version on Msys2 to be updated to version 5.15.3?

It's slim-simulator that should be rebuilt against Qt 5.15.3

**Comment by mmuetzel** [comment]
This should be fixed with the changes proposed in #10955.

You could check if this works for you by downloading the build artifacts for `MINGW64` from the bottom of this page:
https://github.com/msys2/MINGW-packages/actions/runs/1963593664

After that, unzip the file and install the updated package with `pacman -U mingw-w64-x86_64-slim-simulator-3.7.1-2-any.pkg.tar.zst`.

Does it work for you with this updated version of slim-simulator?

**Comment by RoslynHenry** [comment]
Hi, yes this works. Thanks for the fix!
