### ISSUE TITLE
arpack and error with pkg-config

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#11376]
$ pkg-config --libs --static arpack
-LC:/msys64/mingw64/lib -larpack BLAS::BLAS

instead:
-LC:/msys64/mingw64/lib -larpack -lopenblas

**Comment by Biswa96** [comment]
Thank you for reporting this issue.

The build output of arpack provides some hint:

```
   -- BLAS:
      -- link:    F:/msys64/ucrt64/lib/libopenblas.dll.a
   -- LAPACK:
      -- link:    BLAS::BLAS
```

So, I have tried this workaround:

```diff
--- a/arpack-ng-3.8.0/CMakeLists.txt
+++ b/arpack-ng-3.8.0/CMakeLists.txt
@@ -694,7 +694,7 @@
 # Convert (LAPACK|BLAS)_LIBRARIES to -l flags, store in ARPACK_PC_LIBS_PRIVATE.
 # LAPACK_LIBRARIES contains transitive deps, no need to parse BLAS_LIBRARIES.
 set(ARPACK_PC_LIBS_PRIVATE)
-foreach(lib ${LAPACK_LIBRARIES})
+foreach(lib ${BLAS_LIBRARIES})
     get_filename_component(libname ${lib} NAME)
     string(REGEX REPLACE "^lib([^.]+).*$" "-l\\1" libname ${libname})
     list(APPEND ARPACK_PC_LIBS_PRIVATE "${libname}")
```

It fixes the issue in arpack.pc file but arpack_64.pc file has this line `Libs.private: openblas_64`. Maybe need some change in the regex pattern in CMakeLists.txt file in arpack.

I assume the issue comes from `$MINGW_PREFIX/share/cmake/Modules/{FindBLAS.cmake, FindLAPACK.cmake}` files. @mmuetzel Would you like to provide any hint on how to troubleshoot this issue?
