### ISSUE TITLE
x86 gmsh segfaults when mesagl installed

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#11399]
strangely the 64 bit version works though i doubt we do ourselfs any favour keeping the osmesa dll's in the path as they are rather slow becuse of software emulation. 

maybe have PKGCONFIG move the dll's out of path ? to something like /mingw*/share/mesa/runtime.

**Comment by mmuetzel** [comment]
Similar when using mesa with Octave.
However, I'd prefer if it would still be possible to have the option to use OpenGL software rendering with the mesa libraries. There are still a few graphics cards around with a buggy OpenGL implementation in their drivers. Software rendering could be useful in this case. If users prefer their proprietary drivers, they could just not install mesa.
(I'm not sure if this is related to off-screen mesa though...)

Having written that: Since the update to mesa 22.0, I wasn't able to setup a working OpenGL environment when mesa is installed. (I haven't tested very thoroughly though...)

**Comment by revelator** [comment]
could just copy out the dll's from /mingw*/share/mesa/runtime if we really want to use the software emulation :) atleast in that case we dont end up with users thinking the software is broken. btw i tried the 32 bit mesa opengl32.dll and dependencies on glquake and strangely it works there so seems it is gmsh that does like mesa.
