### ISSUE TITLE
Provide make as a symlink to mingw32-make

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#11703]
Please consider providing make.exe as a symlink to mingw32-make.
As a user I expect to find make.exe as part of ${MINGW_PREFIX}-make package.

**Comment by lazka** [comment]
Since they are not compatible I'd be worried that users use the wrong one.

**Comment by MehdiChinoune** [comment]
> Since they are not compatible

Could you elaborate how?
How could a symlink/copy program incompatible with the linked/copied one!

**Comment by naveen521kk** [comment]
>  How could a symlink/copy program incompatible with the linked/copied one!

I think he meant that `make.exe` from [make package](https://packages.msys2.org/base/make) from msys repo is not compatible with `mingw32-make.exe` from the mingw64 repo.

**Comment by mati865** [comment]
Mingw32-make is native application so it uses Windows style paths while make uses Cygwin library and UNIX paths. There were multiple issues over the years when people tried to mix them.

**Comment by revelator** [comment]
could provide it as a gmake symlink since that seems to also use windows paths.

**Comment by revelator** [comment]
or set MAKE=mingw32-make maybe ?.

**Comment by rosti-il** [comment]
> > How could a symlink/copy program incompatible with the linked/copied one!
> 
> I think he meant that `make.exe` from [make package](https://packages.msys2.org/base/make) from msys repo is not compatible with `mingw32-make.exe` from the [mingw64 repo](https://packages.msys2.org/base/mingw-w64-make).

This seems to be not relevant. `make.exe` from the base is most likely in use in MSYS environment only while `make.exe` from the mingw-w64 is most likely in use in MINGW64 only. In the MINGW64 environment the `/mingw64/bin` is very first in the `PATH` while in all other environments `/mingw64/bin` is not included into the `PATH`. So a user can't be confused between those two versions of `make.exe` when working in their appropriate environments. Otherwise what is the purpose of different environments in MSYS2 in general?

I think this bug should be reopened and the `C:\msys64\mingw64\bin\mingw32-make.exe` should be installed with a hardlink (not symlink) to `C:\msys64\mingw64\bin\make.exe` as all other GNU toolchain tools, for example like `x86_64-w64-mingw32-gcc.exe`, `x86_64-w64-mingw32-gcc-14.1.0.exe`, `gcc.exe` and `cc.exe` are copies of the same file within `C:\msys64\mingw64\bin`.
