### ISSUE TITLE
mingw-w64-x86_64-python-pyqt5 missing QtSvg module

### ISSUE THREAD

**Issue by MarioPossamato** [msys2/MINGW-packages#11753]
I don't know if there's something else I need to install, but mingw-w64-x86_64-python-pyqt5 is missing the QtSvg module.

**Comment by Biswa96** [comment]
qt5-svg package is in optional dependencies. You have to manually install it with `pacman -S <package name>` command.

**Comment by MarioPossamato** [comment]
Ah, I see.  Well, there's another issue: it can't find the file.  I'd prefer not to use the absolute path.  Here's the error:
```
qt.svg: Cannot open file 'C:/msys64/mingw64/bin/image.svg', because: The system cannot find the file specified.
```

**Comment by Biswa96** [comment]
Please provide all the steps and commands to reproduce the issue.

**Comment by MarioPossamato** [comment]
- Commands:
```pacman -S mingw-w64-x86_64-python-pyqt5```
```pacman -S mingw-w64-x86_64-qt5-svg```
```pacman -S mingw-w64-x86_64-gdb-multiarch```

- Steps:
Run this [minimal reproducible example](https://github.com/msys2/MINGW-packages/files/8801788/main.py.txt) in gdb-multiarch with the `source` command.

**Comment by Biswa96** [comment]
I put main.py and image.svg in same directory and it does not show any error. But the window is blank, does not show the SVG image.

**Comment by MarioPossamato** [comment]
Ah, it sets image.svg as the window icon.

**Comment by Biswa96** [comment]
So, is this issue solved now?

**Comment by MarioPossamato** [comment]
Unfortunately, I haven't found a fix.  Is there any output at all?  For me, the error appears twice.

**Comment by Biswa96** [comment]
I have installed the packages in a clean mingw64 environment. There is no error in my setup. The python script searches for the svg file in the same directory. You can see the svg file search path with [Process Monitor][1].

[1]: https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by MarioPossamato** [comment]
Huh.  If I open gdb-multiarch inside of a Command Prompt window (that was opened in the same directory as the image), then use the `source` command, it works.  Does that help?

**Comment by Biswa96** [comment]
I am not familiar with python in-depth. Other experts may help.

**Comment by ferdnyc** [comment]
@MarioPossamato 
> Huh. If I open gdb-multiarch inside of a Command Prompt window (that was opened in the same directory as the image), then use the `source` command, it works. Does that help?

...As opposed to... what? How were you running `gdb-multiarch` when you _did_ get the error you originally reported?

I'm with @Biswa96, I tried a bunch of different ways and I couldn't get the test to fail.

If you're running the script from a directory other than the one it's located in, then it's expected the file wouldn't be found. An unqualified path in Python doesn't mean "the same directory as this script", it means "the current working directory of the Python interpreter", which will be whatever directory you ran it from.

So, if you're doing something like this:
```cmd
% cd C:\msys64\clang64\bin\
% python3 C:\Users\Me\main.py
```
...it's expected that would fail, because the script is saying, "Load `image.svg` from the current directory", which is `C:\msys64\clang64\bin\`. (That's consistent with the error you reported.)

If you want to always load the image from the script directory, you have to build the path relative to the script file's location. You can't  just use a bare filename, or any sort of relative path, because it will be relative to the current working directory.

What you **can** do is use `__file__`, a Python magic variable that's set to the location of the currently-executing script. (Beware, though, it won't be defined in all circumstances, such as when running commands in the interactive interpreter.)

So, for example:
```python3
import os

[...]

icon_path = os.path.join(os.path.dirname(__file__), 'image.svg')
self.setWindowIcon(QtGui.QIcon(icon_path))
```

With those changes made, I can run `main.py` from any location and it will still load `image.svg` from the same directory the Python file is located in.

**Comment by MarioPossamato** [comment]
Ah, as opposed to simply opening gdb-multiarch.exe from File Explorer.  I have a shortcut to it on my desktop, and I use that, rather than the Command Prompt.

**Comment by ferdnyc** [comment]
@MarioPossamato Ah, I see!

You **can** set the working directory for a shortcut in its Properties. If you were to configure it so that it always started in the directory where the script lives, that would be another way to tackle this. 

But, really, you're still better off keeping the script working-directory independent, by using `__file__` to construct the path. Or, you can use [`importlib.resources`](https://docs.python.org/3/library/importlib.html#module-importlib.resources), which is another way of solving the same problem. (It also works for packaged files that don't have static filesystem paths, like packages loaded from zip files / wheels.)

**Comment by MarioPossamato** [comment]
Ah, I see!  So, what would be required for the first option?  I'll probably use the second, but it's nice to have options.

**Comment by Biswa96** [comment]
So, this does not look like mingw packages issue but a specific use case in your system, right?

**Comment by MarioPossamato** [comment]
Yeah.

**Comment by ferdnyc** [comment]
@MarioPossamato 
> Ah, I see!  So, what would be required for the first option?  I'll probably use the second, but it's nice to have options.

You just right-click on the shortcut and set the "Start in" field to the (Windows) path of the directory your Python program is saved in. The debugger will start from that path, and so will any relative paths in the code you run.
