### ISSUE TITLE
Meson errors with Python 3.10

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#11864]
It randomly fails when calling into meson scripts:

1) mesa:

> FAILED: src/util/u_unfilled_gen.c 
  "D:/M/msys64/mingw64/bin/meson" "--internal" "exe" "--capture" "src/util/u_unfilled_gen.c" "--" "D:\M\msys64\mingw64\bin/python3.EXE" "../../src/util/indices/u_unfilled_gen.py"

>FAILED: src/gallium/targets/osmesa/osmesa.dll.p/osmesa.dll.symbols 
"D:/M/msys64/mingw64/bin/meson" "--internal" "symbolextractor" "C:/_/mingw-w64-mesa/src/mesa-22.1.2/build/windows-x86_64" src/gallium/targets/osmesa/osmesa.dll "src/gallium/targets/osmesa/osmesa.dll.a" src/gallium/targets/osmesa/osmesa.dll.p/osmesa.dll.symbols 

2) gobject-introspection

> FAILED: girepository/libgirepository-1.0-1.dll.p/libgirepository-1.0-1.dll.symbols 
"D:/a/msys64/clang64/bin/meson" "--internal" "symbolextractor" "C:/M/mingw-w64-gobject-introspection/src/build-x86_64-w64-mingw32" girepository/libgirepository-1.0-1.dll "girepository/libgirepository-1.0.dll.a" girepository/libgirepository-1.0-1.dll.p/libgirepository-1.0-1.dll.symbols 

There was one more packages during the Python rebuild that failed that way (with "symbolextractor" I think), but I didn't write it down sadly.

**Comment by eli-schwartz** [comment]
It's completely bizarre that the symbolextractor fails *without* emitting an error message of any sort. It's reminiscent of https://github.com/pypa/pip/issues/10875 (was a bug in the launcher *.exe files pip uses on Windows).

**Comment by lazka** [comment]
thanks, good point. I can try porting meson from setuptools to builder/installer so it gets a newer launcher.

**Comment by naveen521kk** [comment]
>  (was a bug in the launcher *.exe files pip/distlib uses on Windows, reproducible in CI but not running interactively).

Hmm, meson was built with setuptools launcher which shouldn't have this issue afaik.

**Comment by lazka** [comment]
same error with the python-installer launcher (#11865)

**Comment by eli-schwartz** [comment]
For the record, last I saw the latest version of distlib was the one with the wonky binaries, and pip specifically worked around this by downgrading the bundled distlib and rereleasing.

I'm not sure what other installers do on Windows specifically. They may bundle different versions of distlib.

**Comment by lazka** [comment]
I fetched the meson build dir from a failed CI build, but there is nothing helpful in there.

Just to point out why it might be a different issue: This happens randomly, it sometimes works, sometimes doesn't in CI. It started with the Update to Python 3.10 over the last week, could be a coincidence, but mesa built fine 2 weeks ago.

**Comment by kcgen** [comment]
@lazka , after seeing you mention the issue was intermittent, I've placed our Meson builds in a diaper script to re-run on failure.

Data points:
 - direct: `meson -C build` -- all failing in CI, not one passed
 - direct: `ninja -C build` -- all failing in CI, not one passed
 - wrapped: `scripts/retry_command.sh 2 meson compile -C build` -- 18 back-to-back good runs, no retried needed.

What's interesting is that the retry logic is never needed, making me suspect that running inside a shell wrapper is altering the parent-level runtime space/behavior in a way that Python likes (perhaps stacksize or other low-level stuff inside MSYS2) versus the "direct-launch"  that's giving it troubles. 

Perhaps when specified as a direct CI command:
``` yaml
   run: command
```

Perhaps to reproduce this locally, you'd need to inspect GitHub's code that parses that command. Perhaps it's Go(?) or Python(?) launching `command` as a system-call.

**Comment by lazka** [comment]
I've forward ported an old ninja PR (https://github.com/ninja-build/ninja/pull/1805) to show the exist status and it's STATUS_ACCESS_VIOLATION

**Comment by shermp** [comment]
> Perhaps to reproduce this locally, you'd need to launch the CI YAML run: command using whatever mechanism GitHub is using. Perhaps their CI code is Go(?) or Python(?) launching command as a system-call (and probably wrapped in some security-hardened WSL Docker instance).

They may be using either .NET or NodeJS. That's what their self hosted runner and actions are using respectively at least.

**Comment by naveen521kk** [comment]
> So that could either be the launcher crashing or python itself. I'd guess python itself (?).

Oh wow, interesting.

**Comment by kcgen** [comment]
A user running GDAL was hit with `STATUS_ACCESS_VIOLATION` on Windows, and boosted the stack and environment settings just before launching the rest of the Python script:

``` python
if __name__ == "__main__":
    if sys.platform[:3] == "win":
        sys.setrecursionlimit(10000000)
        threading.stack_size(200000000)
        thread = threading.Thread(target=driver)
        thread.start()

    # ... launch...
```

https://stackoverflow.com/questions/41000945/why-do-i-get-a-status-access-violation-when-i-run-this-python-script-on-windows

**Comment by lb90** [comment]
Hi! Can anyone share a TLDR of this issue? Some Meson internal commands fail randomly and it's unclear whether the problem is in Ninja, Meson or Python 3.10?

**Comment by lb90** [comment]
FWIF, the error in https://github.com/msys2/MINGW-packages/pull/11915 can be reproduced reliably, meaning that it's not random, it simply happens anytime I run ninja. It may be useful to investigate this issue further

**Comment by Biswa96** [comment]
Yeah, the vala error is different topic. I can try to create a PR today to workaround that issue.

**Comment by lb90** [comment]
Ah, thanks! That would be great. I'm not well versed into gtk-doc and vala 🙂

**Comment by lb90** [comment]
Not sure, but maybe those links provide infos about this bug:

* https://github.com/actions/virtual-environments/issues/5027
* https://github.com/actions/setup-python/issues/328

**Comment by lazka** [comment]
> So that could either be the launcher crashing or python itself. I'd guess python itself (?).

it's python itself

**Comment by lazka** [comment]
> A user running GDAL was hit with `STATUS_ACCESS_VIOLATION` on Windows, and configured the stack and environment settings prior to launch:

That's a general CPython problem, it doesn't handle stack overflows properly and can crash. I don't think this is related.

**Comment by naveen521kk** [comment]
Enabling verbose mode makes the crash disappear (tried it quite some times). Not sure if it gives any hint on where exactly the issue is. 

Also, maybe we should try reverting https://github.com/msys2/MINGW-packages/commit/b26a07e7deae1fb1da7b65e40ebe9c3fe75dd59f and see if it fixes any issues?

**Comment by lazka** [comment]
> Also, maybe we should try reverting [b26a07e](https://github.com/msys2/MINGW-packages/commit/b26a07e7deae1fb1da7b65e40ebe9c3fe75dd59f) and see if it fixes any issues?

The error happened before that already.

**Comment by eli-schwartz** [comment]
> > So that could either be the launcher crashing or python itself. I'd guess python itself (?).
> 
> it's python itself..

This is now reproducing on Meson's CI: https://github.com/mesonbuild/meson/pull/10613#issuecomment-1188267017

Which incidentally does not use any launchers, so that's publicly logged confirmation that yep, it's definitely python itself.

**Comment by lb90** [comment]
Is it possible to register a JIT debugger (e.g gdb) in the CI runners? https://docs.microsoft.com/en-us/windows/win32/debug/configuring-automatic-debugging

**Comment by lazka** [comment]
> Is it possible to register a JIT debugger (e.g gdb) in the CI runners? https://docs.microsoft.com/en-us/windows/win32/debug/configuring-automatic-debugging#configuring-automatic-debugging-for-application-crashes

I'm going to look into this next.

**Comment by lazka** [comment]
Enabling JIT debugging makes the error go away. But at this point I'm just happy to have a workaround for CI.

**Comment by jeremyd2019** [comment]
A downside of the workaround of setting `winjitdebug` option (and the reason we gated it behind an option in the first place) is that now in case of some Windows errors (such as DLL not found, no disk in drive, ...) Windows will show a message box.  In the situation of CI, there's nobody to see the message box or answer it, so the build appears to just hang, rather than erroring out as it would have without the option.

**Comment by lazka** [comment]
Yeah, I was worried about that, but it seemed like the lesser evil at that point. (did the arm runner hang at any point because of this? I didn't see any occurrence in the GHA CI at least)

**Comment by lazka** [comment]
ah, right now in CI probably, as mentioned in discord

**Comment by anarazel** [comment]
@lazka:
> Enabling JIT debugging ([6ff1a1f](https://github.com/msys2/MINGW-packages/commit/6ff1a1f8a631ab9b243a827e77619dc2f33cb992)) makes the error go away. But at this point I'm just happy to have a workaround for CI.

I suspect that might be because setting MSYS=winjitdebug causes the error-mode for children to be set to 0. Normally that's set to SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX (in normal windows at least). Not having SEM_FAILCRITICALERRORS will cause a bunch of behavioural differences, which could easily prevent the crash from occurring. 

```
myadmin@win10-nojoin UCRT64 ~
$ python -c "import msvcrt; print(hex(msvcrt.GetErrorMode()))"
0x3

$ export MSYS=winjitdebug
$ exec bash

myadmin@win10-nojoin UCRT64 ~
$ python -c "import msvcrt; print(hex(msvcrt.GetErrorMode()))"
0x0
```

**Comment by anarazel** [comment]
Turns out it's actually the presence of SEM_NOOPENFILEERRORBOX - I can, very very occasionally, reproduce crashes after os._exit() and before process exit. So this looks very likely to be a microsoft C runtime (or kernel) bug. In my case no msys environment is involved, fwiw.

**Comment by lb90** [comment]
Could be a DLL doing weird things from their `DLL_PROCESS_DETACH`? (or the same from a TLS callback)

Actually in `DLL_PROCESS_DETACH` a DLL should check whether the process is exiting (`lpvReserved != nullptr`), and in that case do nothing at all. The program state is undefined:

* https://devblogs.microsoft.com/oldnewthing/20150213-00/?p=44683
* https://devblogs.microsoft.com/oldnewthing/20070503-00/?p=27003

Also documented on MSDN:

* https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain
* https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices#best-practices-for-synchronization

Unfortunately many DLLs don't do that

**Comment by anarazel** [comment]
> Could it be a DLL doing weird things from their DLL_PROCESS_DETACH then? (or the same from a TLS callback)

A quick grep through the python sources doesn't show a problematic DLL_PROCESS_DETACH callback that could be involved here. None of them do anything in the DLL_PROCESS_DETACH case.  I didn't see any tls callbacks at all, but might be missing something (not a windows person).

Given the crash only happens with SEM_NOOPENFILEERRORBOX set it seems more likely to be a bug in the CRT or kernel to me, since that being set should lead to *less* application involvement.

**Comment by lb90** [comment]
>  I can, very very occasionally, reproduce crashes after os._exit() and before process exit

Can you reproduce locally? If so, may I ask how are you invoking python?

**Comment by anarazel** [comment]
> Can you reproduce locally? If so, may I ask how are you invoking python?

Unfortunately only in CI, windows 2019 in my case. The method of invoking python doesn't seem to matter, it happens even when invoking via path/to/python.exe path/to/script.py

**Comment by jeremyd2019** [comment]
Thought I'd try to correct the record a bit here since this got referenced again.  error mode `0x3` is actually `SEM_FAILCRITICALERRORS|SEM_NOGPFAULTERRORBOX`.  Both relate to not showing a message box if an error occurs.  Unfortunately, MS hooked just-in-time debugging (and WER) to the "GP fault error box" path, so if you disable that you cannot get those either.  This is why the option I added is called `winjitdebug` (because that's what I was trying to enable).  Also, mode `0x0` should be the OS default (though the default is also to inherit from the parent process, so you can't necessarily assume what they will be).

**Comment by anarazel** [comment]
>  Also, mode 0x0 should be the OS default (though the default is also to inherit from the parent process, so you can't necessarily assume what they will

Oh, indeed. I saw 0x8001 because I was using the 'terminal app' to start cmd, rather than just cmd.exe directly. Extremely unhelpful by terminal to start the "sub terminals" with a different error mode than normal...

> Thought I'd try to correct the record a bit here since this got referenced again. error mode 0x3 is actually SEM_FAILCRITICALERRORS|SEM_NOGPFAULTERRORBOX.

The reference to SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX was not about the 0x3, but what I saw in the windows terminal. 0x3 / SEM_FAILCRITICALERRORS|SEM_NOGPFAULTERRORBOX is what some msys code sets when MSYS=winjitdebug isn't set.

**Comment by lb90** [comment]
Regarding this, how would one go about setting up Github action that can reproduce the error?

**Comment by vintagepc** [comment]
It seems to happen fairly consistently with the MSYS build in my project repo linked in the referenced issue from 6h ago as it does a fairly involved Meson/Python build.

https://github.com/vintagepc/MINI404/pull/116 has been giving me grief most recently.

**Comment by vintagepc** [comment]
I'll add in that I just tried force-downgrading to the mingw64 python 3.9 package and it seems to have made the problem go away - will rerun the workflow a few times to confirm.

**Comment by lazka** [comment]
We've made some progress finding a potential cause here: https://github.com/msys2/MINGW-packages/issues/17415

With a bit of luck the update to 3.11 will fix this.

**Comment by lazka** [comment]
I'm closing this in favor of #17415

**Comment by lazka** [comment]
One last comment here: We've updated to Python 3.11 yesterday, so this should no longer be an issue.
