### ISSUE TITLE
wxWidgets packaging rules and requests impossible to follow

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#12203]
I was requested to not require people to use the new wxWidgets package of 3.2.0
I was told the packages names where wrong; that was okay.
I was told we do not package just the DLLs. This is not okay.

Since, it is not possible to follow all of the above I have given up try to make an wxWidgets 3.2.0 package I will let some other person fight to do it.

Wish you luck; but, I am afraid MSys2 will die out if this trend continues.

Tim S.

**Comment by ZachBacon** [comment]
I'm sorry you felt frustrated, and to be honest, I know the pain, I've run into some of the issues myself contributing. But since 3.2.0 is technically the new stable (at the time my concern was... that it was still kinda in testing, not knowing that not even a day later it became the final release) I do think wxwidgets 3.0 can be dropped in favour of 3.2 myself now. But it's not really my call in that regard.
