### ISSUE TITLE
package mingw-w64-clang-x86_64-rust should target to x86_64-pc-windows-gnullvm

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/MINGW-packages#13388]
As there's only **llvm-based** toolchain in ucrt64 repo ,the target **x86_64-pc-windows-gnu** is not the proper one ,and it doesn't work even with package **mingw-w64-clang-x86_64-gcc-compat** installed.

**Comment by jeremyd2019** [comment]
I think that's being worked on, #13278 is related

**Comment by mati865** [comment]
> As there's only llvm-based toolchain in ucrt64 repo

UCRT64 repo is GCC/Binutils based, CLANG64 is LLVM based.

> the target x86_64-pc-windows-gnu is not the proper one ,and it doesn't work

It works fine because of hacks, we have compiled multiple packages with it: https://packages.msys2.org/package/mingw-w64-clang-x86_64-rust

> mingw-w64-clang-x86_64-rust should target to x86_64-pc-windows-gnullvm

That is long-term goal but:
1. Getting it to build with pacman under MSYS2 has been troublesome and so far it's even more hacky than using regular `*-pc-windows-gnu` triples.
2. Ecosystem is not ready yet, because of the dependencies migrating right now would break building half of the packages (or more) that we already build with Rust for CLANG64.
