### ISSUE TITLE
MinGW-w64 runtime license not included in package

### ISSUE THREAD

**Issue by timedroid** [msys2/MINGW-packages#1490]
As far as I understand, programs compiled with a MinGW-w64 compiler statically link against the runtime and are required to include [COPYING.MinGW-w64-runtime.txt](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/COPYING.MinGW-w64-runtime/COPYING.MinGW-w64-runtime.txt).

I see copyright notices for winpthreads in the MSYS2 distribution, but I can't find anything for the runtime as a whole (which includes bits from other authors as well); thus it seems MSYS2 is technically violating the license. Please correct me if I'm wrong.

**Comment by Ghostkeeper** [comment]
IANAL, but if I understood it correctly, this repository does not distribute the MinGW-w64 runtime, in code or binary form. This means that the license does not need to be included.

If someone were to use this repository to compile a program or library, and statically link it against the runtime, they would need to include their license with the compiled (and statically linking) release, since they are redistributing the runtime then.

**Comment by lazka** [comment]
I guess someone could include the license file here: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-crt-git/PKGBUILD

**Comment by MehdiChinoune** [comment]
Fixed by https://github.com/msys2/MINGW-packages/commit/7984c08b9cdfaa888609f372a43b9d913c28be74
