### ISSUE TITLE
boost-1.81.0-2 tries to link to non-existant libs icudata, icui18n

### ISSUE THREAD

**Issue by kintel** [msys2/MINGW-packages#15021]
### Description / Steps to reproduce the issue

1. Install boost
2. Configure an app using the new BoostConfig.cmake
3. Link with boost regex

Diagnosis:

This happened after updating boost from 1.81.0-1 to 1.81.0-2.
This PR looks like the culprit: https://github.com/msys2/MINGW-packages/pull/14790

The generated boost regex cmake file contains
```
set_property(TARGET Boost::regex APPEND PROPERTY INTERFACE_LINK_LIBRARIES icudata icui18n icuuc)`
```

The issue in action can be observed here: https://github.com/openscad/openscad/actions/runs/3834393932/jobs/6627771341

Suggested quick-fix: Roll back https://github.com/msys2/MINGW-packages/pull/14790 and release boost-1.81.0-3.

### Expected behavior

I can can link boost regex into an executable.

### Actual behavior

```
D:/a/_temp/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licudata: No such file or directory
D:/a/_temp/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -licui18n: No such file or directory
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows Server 2022   10.0.20348   Datacenter

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Yes

**Comment by jordanbrown0** [comment]
It doesn't affect OpenSCAD, but it looks like there are several other boost components with the same problem:
```
/mingw64/lib/cmake/boost_graph-1.81.0/libboost_graph-variant-mt-static.cmake
/mingw64/lib/cmake/boost_locale-1.81.0/libboost_locale-variant-mt-static.cmake
/mingw64/lib/cmake/boost_log-1.81.0/libboost_log-variant-mt-static.cmake
/mingw64/lib/cmake/boost_log_setup-1.81.0/libboost_log_setup-variant-mt-static.cmake
/mingw64/lib/cmake/boost_regex-1.81.0/libboost_regex-variant-mt-static.cmake
```

**Comment by Biswa96** [comment]
@slavaandrejev Would you like look into this issue please?

**Comment by slavaandrejev** [comment]
Yes, I am on it.

**Comment by slavaandrejev** [comment]
Foremost, thank you for bringing this issue to our attention. Boost is not perfect, it all requires fixing, and a report like this is definitely will steer us to the right direction. My guess is that the culprit is `remap-library` function from [this](https://github.com/boostorg/boost_install/commit/3e6c7e53712ddca416f33cfce0f685df8ca8343a) commit. The commit message doesn't give me any clue why this function was introduced and why it changes the names of the libraries. I will try to ask @pdimov later, but for now, let me just try to remove this remapping,

**Comment by slavaandrejev** [comment]
Since you reverted the change, I have to ask do you guys need my help in fixing boost? I was like 2 minutes out of submitting the correct solution to the problem. Why was I doing it at 2am?

**Comment by kintel** [comment]
While the rollback fixes the breakage, it doesn’t address the root cause, so a proper fix would still be valuable.

**Comment by pdimov** [comment]
The remapping in the mentioned commithttps://github.com/boostorg/boost_install/commit/3e6c7e53712ddca416f33cfce0f685df8ca8343a takes care of the default case, where the libraries are named as in the remapper (https://github.com/boostorg/regex/blob/237e69caf65906d0313c9b852541b07fa84a99c1/build/Jamfile.v2#L78, https://github.com/boostorg/regex/blob/237e69caf65906d0313c9b852541b07fa84a99c1/build/Jamfile.v2#L92.) This is necessary for Linux (and I think macOS) to work.

In this case however, the names are overridden from the command line with
```
    -sICU_ICUUC_NAME=icuuc \
    -sICU_ICUDT_NAME=icudt \
    -sICU_ICUIN_NAME=icuin \
```
so rather than removing the remapping, a better fix would be to remap to `$(ICU_ICUUC_NAME)`, `$(ICU_ICUDT_NAME)` and `$(ICU_ICUIN_NAME)` instead.

I'll look into preparing a candidate patch, although I'm not sure I can test it.

**Comment by slavaandrejev** [comment]
> While the rollback fixes the breakage, it doesn’t address the root cause, so a proper fix would still be valuable.

Yeah, it's just I was asked to look at it, I announced that I am working on it, then dived into it like a firefighter, after midnight, then the rollback happened. Guys, can we collaborate and coordinate more to value each other time? I would like to help with boost more, there are numerous problems with the package. For example, we compile it without optimization options.

I will remove this complaint.

**Comment by pdimov** [comment]
I'm interested in fixing this on the Boost side, regardless of whether the rollback is rolled back or not. :-)

**Comment by slavaandrejev** [comment]
@pdimov If you publish a patch here, I will test it and prepare a PR. Thank you for help!

**Comment by pdimov** [comment]
This is the tentative fix: https://github.com/boostorg/boost_install/commit/ef9d85695388e252c63f05ab735af6d989c092e1

**Comment by slavaandrejev** [comment]
> Just want to make sure, do you think those ICU_ICU*_NAME option should be removed from build command in pkgbuild?

They should not. My plan is to extract them from pkg-config.

**Comment by pdimov** [comment]
No, they still need to be there, and the fix depends on them being there.

The fix seems to work for me locally. Let me know how it fares for your build.

**Comment by slavaandrejev** [comment]
I am preparing a PR.

**Comment by lazka** [comment]
(reverted now)

**Comment by t-paul** [comment]
Thanks! I can confirm successful build using `mingw-w64-ucrt-x86_64-boost-1.81.0-3`.

Log https://github.com/openscad/openscad/actions/runs/3889369594/jobs/6652095469

**Comment by lazka** [comment]
Thanks for testing

**Comment by kintel** [comment]
The `-4` package also got picked up this morning, and it works too!
