### ISSUE TITLE
Clang: Sporadic linker errors happen when a sysroot is used

### ISSUE THREAD

**Issue by rvogg** [msys2/MINGW-packages#15695]
### Description / Steps to reproduce the issue

If you use clang as a cross compiler and give it a new sysroot via the --sysroot this error can occur sporadically. 

We have a very large CMake project. When we build the project in CI, we sometimes get build errors. However, this is highly sporadic and occurs in about 1% of linker actions.

Locally you can reproduce it if you update the sysroot folder access time during the build. (`while true; do touch -a <sysroot> ; done`) 

The comparison of access times was introduced with http://reviews.llvm.org/D18456. I think this happened by mistake.

### Expected behavior

lld should not have sporadic errors and should link independent of the access time.

### Actual behavior

lld sporadically fails to resolve GNU linker scripts.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?
https://github.com/msys2/MINGW-packages/pull/15694

**Comment by mstorsjo** [comment]
Can you add in some more details about what actually goes wrong? The only detail here is "When we build the project in CI, we sometimes get build errors."

The patch mentions that `isUnderSysroot` gets set incorrectly. Can you explain what this variable is, where it gets set, what you do in your surrounding build environment which causes the access time checks to cause problems, etc.

Really explain the whole issue, step by step, from the ground up - otherwise it's impossible to judge the patch and the issue.

**Comment by rvogg** [comment]
Okay, the long version: 

- We use clang as a second compiler to cross-compile to a linux system. For this we give the clang the gcc-linux-sysroot as syssroot. 
- If we now compile in CI (with higher latencies between the single instructions) or local strongly parallelized, we sometimes get the error 
  `ld.lld: error: cannot open /lib/libc.so.6: No such file or directory`.
 
- The path `/lib/libc.so.6` comes from the file `/usr/lib/libc.so` , which is a GNU ld script. 

- After analyzing in lld, I found that this can only occur when https://github.com/llvm/llvm-project/blob/main/lld/ELF/ScriptParser.cpp#L293 is not true. 

- The only place where the variable isUnderSysroot can be affected is: https://github.com/llvm/llvm-project/blob/main/lld/ELF/ScriptParser.cpp#L56

- The function  `sys::fs::equivalent(...)` compares two file paths whether they are identical (under Linux the inodes are used for this).
  - The Windows version uses the implementation patched in the PR.
  - A stat is made on one file, then a stat on the other.

### Now for the race condition: 

If the sysroot folder is accessed while the function `sys::fs::equivalent(...)` is executed on it, the function returns `false`. This results in `isUnderSysroot` also being `false` and `/lib/libc.so.6` being used without sysroot prefix.

When building massively in parallel (sysroot is used very often) or building in visualized CI (the gap between the two stats is larger) the error occurs more often.

**Comment by mstorsjo** [comment]
> Okay, the long version:
> 
> * We use clang as a second compiler to cross-compile to a linux system. For this we give the clang the gcc-linux-sysroot as syssroot.
> * If we now compile in CI (with higher latencies between the single instructions) or local strongly parallelized, we sometimes get the error
>   `ld.lld: error: cannot open /lib/libc.so.6: No such file or directory`.
> * The path `/lib/libc.so.6` comes from the file `/usr/lib/libc.so` , which is a GNU ld script.
> * After analyzing in lld, I found that this can only occur when https://github.com/llvm/llvm-project/blob/main/lld/ELF/ScriptParser.cpp#L293 is not true.

Ok, thanks, I'm following this far; the linker looks things up differently if operating under a sysroot, and here we explicitly set a sysroot and want the linker to respect t hat.

> * The only place where the variable isUnderSysroot can be affected is: https://github.com/llvm/llvm-project/blob/main/lld/ELF/ScriptParser.cpp#L56
> * The function  `sys::fs::equivalent(...)` compares two file paths whether they are identical (under Linux the inodes are used for this).
>   
>   * The Windows version uses the implementation patched in the PR.
>   * A stat is made on one file, then a stat on the other.

As you have debugged and traced this, and I haven't - what paths are compared here with `sys::fs::equivalent` (and from the LLD logic point of view - why?)

I presume on unix systems, the idea is that you can have `equivalent("/foo", "/bar")`, if the two directories practically evaluate to the same due to links etc. In the case of linking with a sysroot - what actual paths are compared here? Are they directories or files?

In one sense, I feel that there should be a fastpath for `equivalent` - `equivalent(A, A)` should trivially return true.

On the other hand, I see the argument that `equivalent(path, path)` shouldn't care about access times. For `equivalent(file_status, file_status)` one maybe could argue that it really should look at all of `file_status` - but if the unix implementation specifically just checks for file identity based on `st_dev` and `st_ino`. So with that in mind, the suggested patch probably is correct as well.

> ### Now for the race condition:
> If the sysroot folder is accessed while the function `sys::fs::equivalent(...)` is executed on it, the function returns `false`. This results in `isUnderSysroot` also being `false` and `/lib/libc.so.6` being used without sysroot prefix.

Right, so if a different process is accessing the sysroot folder while LLD is inspecting the tree - in particular, when doing `equivalent(A, A)`, if it is accessed after the first `status(A)` but before the second, the equivalent check fails. And that's a clear race condition and a bug.

I believe this is clear enough that it definitely should be fixed in upstream LLVM; I can take the patch further upstream there after finishing the discussion here.

**Comment by rvogg** [comment]
> As you have debugged and traced this, and I haven't - what paths are compared here with `sys::fs::equivalent` (and from the LLD logic point of view - why?)

It checks if the absolute path of the ld script is in the sysroot folder. 
```
for (; !path.empty(); path = sys::path::parent_path(path)) {
      if (!sys::fs::equivalent(config->sysroot, path))
        continue;
      isUnderSysroot = true;
      return;
    }
```

1. `sys::fs::equivalent(config->sysroot, "<sysroot>/usr/lib/libc.so")` -> `false`
2. `sys::fs::equivalent(config->sysroot, "<sysroot>/usr/lib")` -> `false`
3. `sys::fs::equivalent(config->sysroot, "<sysroot>/usr")` -> `false`
4. `sys::fs::equivalent(config->sysroot, "<sysroot>/")` -> `true`



> I presume on unix systems, the idea is that you can have `equivalent("/foo", "/bar")`, if the two directories practically evaluate to the same due to links etc. In the case of linking with a sysroot - what actual paths are compared here? Are they directories or files?

As far as I understand it, only the sysroot directory is compared. 
With windows 10, it is quite possible that symlinks are also used in Windows. (For example, our sysroot is also under a symlink). 

> In one sense, I feel that there should be a fastpath for `equivalent` - `equivalent(A, A)` should trivially return true.

That would make perfect sense. 
I've thought about it too, but wanted to keep it minimal for now.

> On the other hand, I see the argument that `equivalent(path, path)` shouldn't care about access times. For `equivalent(file_status, file_status)` one maybe could argue that it really should look at all of `file_status` - but if the unix implementation specifically just checks for file identity based on `st_dev` and `st_ino`. So with that in mind, the suggested patch probably is correct as well.

As far as I have seen, it is only used to see if two paths reference the same object. 
If it has already been identified as identical by the IDs, the comparison on access times no longer makes sense. 
Alternatively I have already thought about a buissy loop. 
```
std::error_code equivalent(const Twine &A, const Twine &B, bool &result) {
  file_status fsA, fsB, controlFsA, controlFsB;
  do{
    if (std::error_code ec = status(A, fsA))
      return ec;
    if (std::error_code ec = status(B, fsB))
      return ec;
    if (std::error_code ec = status(A, controlFsA))
      return ec;
    if (std::error_code ec = status(B, controlFsB))
      return ec;
  }while( !equivalent(fsA, controlFsA) || !equivalent(fsB, controlFsB) );
  result = equivalent(fsA, fsB);
  return std::error_code();
}
```
That should fix the problem as well.

**Comment by mstorsjo** [comment]
The patch has been merged upstream, in https://github.com/llvm/llvm-project/commit/a1e80c69223a091e6f0fc84df33a464604c8bbc1 - and I filed a backport request to the upcoming 16.x release in https://github.com/llvm/llvm-project/issues/60833.
