### ISSUE TITLE
Build Qt with opengl=dynamic or opengl=angle by default

### ISSUE THREAD

**Issue by nickdiego** [msys2/MINGW-packages#1649]
From [1] and [2] Qt supports choosing and loading the OpenGL implementation at runtime. When a given environment fails to provide a proper OpenGL 2.0 implementation, it will fall back automatically to ANGLE. This fallback will be completely transparent to the application, and will allow Qt Quick or other OpenGL code to function by translating to Direct3D. Such a fallback could, for example, take place on a Windows 7 PC with no additional graphics drivers installed.
Looking at the git logs, I realized that you disabled "dynamic" opengl config because it's "was not working", so I wonder is that an issue with Upstream Qt stuff or a packaging issue?
Since the official Qt binary packages come with "opengl=dynamic" it would be desirable msys2 package to use that option as well, if that's not possible at this moment, I think it's better to use "angle" as default, which was the default option before Qt 5.5 and "dynamic" option. That's very helpful, for example, in my case I'm trying to use msys2 Qt5.6 to create a Qt Quick 2 app, it compiles ok but when I try to run it, it fails when trying to render opengl stuff using Microsoft implementation, and I'm not able is not feasible to our target user base to switch to a more modern video cards, etc.

[1] http://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers
[2] https://blog.qt.io/blog/2014/11/27/qt-weekly-21-dynamic-opengl-implementation-loading-in-qt-5-4

**Comment by Martchus** [comment]
Note: I'm developing mingw-w64-qt5 packages for Arch Linux which is quite similar but there might be some differences though.

Last time I tried to use the dynamic switch it didn't work (don't remember the exact error).

> Since the official Qt binary packages come with "opengl=dynamic" ...

Where did you read that? Note that the MSVC version might use the dynamic option whereas the MinGW version still defaults to non-dynamic OpenGL.

Just try to compile Qt with _opengl=dynamic yourself. If you ran into errors you can add them here or experiment a little bit yourself. If you don't need it you can speed up compilation by disabling Qt WebKit.

Please note that ANGLE is in my experience a problematic dependency because its PKGBUILD is hard to maintain. I'm not sure whether ANGLE currently builds using the PKGBUILD provided in this repo. It seems to not stick to a particular commit. The last commit I successfully built under Arch was 5858f7e but I can not build the latest master currently. Additionally, a workaround for building static libraries is required, concurrent builds are broken and I suppose building with mingw-w64 is not even officially supported. Hence I don't put too much effort in the dynamic switch because it is useless if I can not build ANGLE anyways.
However, you could also try to use the ANGLE bundled with Qt. (This would mean to comment out patches like 0020-qt-5.3.0-use-external-angle-library.patch.)

**Comment by nickdiego** [comment]
Hi @Martchus 
Thanks for your attention.

So, I've read about opengl=dynamic in official binaries [here](http://doc.qt.io/qt-5/windows-requirements.html#dynamically-loading-graphics-drivers):
> Note: As of Qt 5.5 this is the configuration used by the official, pre-built binary packages of Qt. It is strongly recommended to use it also in custom builds, especially for Qt binaries that are deployed alongside applications.

> Note that the MSVC version might use the dynamic option whereas the MinGW version still defaults to non-dynamic OpenGL.
So "official binary packages" in this case means only MSVC toolchain?

About experimenting with the PKGBUILDs myself, I'll do that as soon as I have some spare time. As I told, I came across this issue when developing an Qt Quick application, which has a short time frame to be delivered :( so that I don't have too much time to focus on the packaging issue right now.

**Comment by nickdiego** [comment]
@Martchus 
Just tested a simple Qt Quick 2 app, using official windows binaries from Qt, and using both MSVC and MingW toolchains and it seems to *dynamically* choose the opengl version to use, here's the output with `QT_LOGGING_RULES=qt.qpa.gl=true`:

`Starting C:\sandbox\build-quick-test-Desktop_Qt_5_7_0_MinGW_32bit-Debug\debug\quick-test.exe...`
`QML debugging is enabled. Only use this in a safe environment.`
`qt.qpa.gl: Basic wglCreateContext gives version 1.1`
`qt.qpa.gl: OpenGL version too low`
`qt.qpa.gl: OpenGL 2.0 entry points not found`
`qt.qpa.gl: GPU features: QSet()`
`qt.qpa.gl: supportedRenderers GpuDescription(vendorId=0x80ee, deviceId=0xbeef, subSysId=0x0, revision=0, driver: "VBoxDispD3D-x86.dll", version=5.1.2.8956, "VirtualBox Graphics Adapter for Windows 8+") renderer:  QFlags(0x2|0x4|0x8|0x20)`
`qt.qpa.gl: Qt: Using EGL from libEGLd`
`qt.qpa.gl: Qt: Using OpenGL ES 2.0 from libGLESv2d`
`qt.qpa.gl: create Created EGL display 0x187fd5a8 v 1 . 4`
`qt.qpa.gl: createPlatformOpenGLContext QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0)`

**Comment by rossy** [comment]
+1. We know from experience in mpv how buggy OpenGL can be on Windows. It would be great to have the option of using ANGLE, especially for developing mpv frontends in Qt, since mpv and Qt can share the same OpenGL/GLES context. Like @Martchus said, ANGLE can be a problematic dependency to build, but I think the ANGLE build in the MSYS2 repo at the moment is recent enough for this purpose.

**Comment by fluffypony** [comment]
Just adding a +1 to this - without it we'll have to ask users to build QT from scratch if they want to compile Windows bins themselves.

**Comment by Martchus** [comment]
I managed to build latest ANGLE using depot-tools and ninja. That way ANGLE becomes a little bit more unproblematic (concurrent building works that way for example).

In case you want to update mingw-w64-angleproject here as well: https://github.com/Martchus/PKGBUILDs/blob/master/angleproject/mingw-w64/PKGBUILD

**Comment by aquiles2k** [comment]
Is there any progress on this? The dynamic OpenGL qt would be very needed for a lots of older Win7 laptops/desktops wanting to run more modern QML interfaces.

**Comment by Martchus** [comment]
I haven't tested OpenGL related features with my Arch packages for quite a while (and also not yet the dynamic config). But it builds with recent ANGLE and it might work. After the update to Qt 5.8 it wasn't even required to patch the configure script anymore to allow ANGLE/dynamic configuration.

**Comment by aquiles2k** [comment]
Oh ok? I looked at https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt5/PKGBUILD#L80 and it seemed like this is still uncommented. Or am i looking at the wrong file?

**Comment by Martchus** [comment]
I'm talking about my Arch Linux packages (https://github.com/Martchus/PKGBUILDs) which work very similar (same package format, the difference is that my packages are built under Arch Linux).

But note that there can be only one config selected at a time and just the default one is currently still desktop. So you can try to select dynamic and it might work (not sure whether anyone has tested it already).

**Comment by aquiles2k** [comment]
So i tried building it with msys2 using instructions from [here](https://wiki.qt.io/MSYS2#Initial_Setup_of_MSYS2) but sadly it failed. Msys2 was freshly installed and updated to latest versions. I just commented line 79 and uncommented line 80 so that _opengl=dynamic was valid. 

When building it fails with: 
```
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest1.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest2.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest3.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest4.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest5.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/registry_controlled_domains/effective_tld_names_unittest6.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/net/base/stale_while_revalidate_experiment_domains.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/third_party/WebKit/Source/platform/ColorData.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/third_party/yasm/source/patched-yasm/modules/arch/x86/x86cpu.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/third_party/yasm/source/patched-yasm/modules/arch/x86/x86regtmod.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/third_party/yasm/source/patched-yasm/x86insn_gas.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtwebengine/src/3rdparty/chromium/third_party/yasm/source/patched-yasm/x86insn_nasm.gperf wird ins Unix-Format umgewandelt …
dos2unix: Datei ./qtxmlpatterns/src/xmlpatterns/parser/TokenLookup.gperf wird ins Unix-Format umgewandelt …
patching file qtbase/src/sql/configure.json
patching file qtbase/configure.bat
patching file qtbase/src/gui/configure.json
patching file qtbase/bin/syncqt.pl
Hunk #1 succeeded at 219 with fuzz 1 (offset 5 lines).
patching file qtbase/src/angle/src/compiler/preprocessor/preprocessor.pro
Hunk #1 succeeded at 43 (offset 2 lines).
patching file qtbase/src/angle/src/compiler/translator.pro
Hunk #1 succeeded at 179 (offset 16 lines).
patching file mkspecs/features/default_post.prf
Hunk #1 succeeded at 65 with fuzz 1 (offset 4 lines).
patching file mkspecs/win32-g++/qmake.conf
Hunk #1 succeeded at 83 with fuzz 2 (offset 9 lines).
patching file mkspecs/features/create_cmake.prf
Hunk #1 succeeded at 236 (offset 22 lines).
patching file mkspecs/win32-g++/qmake.conf
Hunk #1 succeeded at 94 (offset 2 lines).
patching file qmake/generators/win32/winmakefile.cpp
Hunk #1 succeeded at 80 (offset -5 lines).
Hunk #2 succeeded at 235 (offset -2 lines).
patching file configure.json
patching file qtbase/src/platformsupport/fontdatabases/fontdatabases.pro
patching file qtdeclarative/examples/quick/tutorials/gettingStartedQml/filedialog/filedialog.pro
patching file qtdeclarative/examples/qml/tutorials/extending-qml/chapter6-plugins/import/import.pro
patching file qtsensors/examples/sensors/grue/import/import.pro
patching file qtsensors/examples/sensors/sensor_explorer/import/import.pro
patching file qtbase/src/gui/Qt5GuiConfigExtras.cmake.in
patching file qtbase/src/gui/gui.pro
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file qtbase/src/gui/gui.pro.rej
patching file qtbase/src/opengl/opengl.pro
Hunk #1 succeeded at 12 with fuzz 2 (offset -1 lines).
patching file qtbase/src/plugins/platforms/windows/windows.pri
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file qtbase/src/plugins/platforms/windows/windows.pri.rej
patching file qtbase/src/src.pro
Hunk #1 FAILED at 155.
1 out of 1 hunk FAILED -- saving rejects to file qtbase/src/src.pro.rej
patching file qtbase/src/plugins/platforms/windows/qwindowseglcontext.cpp
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file qtbase/src/plugins/platforms/windows/qwindowseglcontext.cpp.rej
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...

```

Im new to manually building the mingw packages, did i miss something?

**Comment by Martchus** [comment]
The problem is that patches can not be applied. That means you did nothing wrong. There is just some rebasing work required. Note that Qt 5.8 includes a huge rework of the configuration system so a lot of things have changed. For my Arch packages I manage all patches for 5.8 under https://github.com/Martchus/qtbase/commits/5.8.0-mingw-w64. Maybe you can use some. As already said, ANGLE/dynamic config is not really tested in my Arch packages but at least patches for it are rebased.

**Comment by neclepsio** [comment]
I also need an ANGLE build: with my graphics card text in check boxes and other controls is not displayed.
