### ISSUE TITLE
[Investigation] The MSYS2 + meson + Python crash issue

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#17415]
Another issue (old one: https://github.com/msys2/MINGW-packages/issues/11864) to collect some information and what was tried so far.

I've created a small repo for reproducing the issue: https://github.com/lazka/python-crash-test

Any ideas regarding what we could try welcome.

## The issue

meson fails with STATUS_ACCESS_VIOLATION sometimes like this when being called from ninja, and we haven't found a way to reproduce it locally:

```
FAILED: libmy-shared-lib6.dll.p/libmy-shared-lib6.dll.symbols 
"D:/a/_temp/msys64/ucrt64/bin/meson" "--internal" "symbolextractor" "D:/a/python-crash-test/python-crash-test/project/_build" libmy-shared-lib6.dll "libmy-shared-lib6.dll.a" libmy-shared-lib6.dll.p/libmy-shared-lib6.dll.symbols 
```

**This below is now out of date, see the followup answers for the cause**

## When has it started

* When we updated from Python 3.9 to 3.10

## Where it failed so far

* It happened in:
  * MINGW64: https://github.com/msys2/msys2-tests/actions/runs/5117107910/jobs/9199890976
  * UCRT64: https://github.com/lazka/python-crash-test/actions/runs/5156416563/jobs/9287390420#step:4:68
  * CLANG64: https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/456

* It happend with:
  * GHA Windows Server 2022
  * GHA Windows Server 2019
  * Gitlab CI using Windows Server 2016

## Where it hasn't failed so far

* In MINGW32 / CLANG32
* Locally, outside of CI

## What makes the error go away

* Running everything via powershell  (and just setting PATH), and not from bash
* Setting `MSYS=winjitdebug`
* Downgrading to our last Python 3.9 mingw version (I created a [rebuild](https://github.com/lazka/python-crash-test/releases/download/temp/mingw-w64-ucrt-x86_64-python-3.9.13-2-any.pkg.tar.zst) for the last version we had)
* Using the official CPython 3.9 installed via setup-python
* Using the official CPython 3.11 installed via setup-python

## What doesn't make the error go away

* Disabling Python forward-slash-path mode via `MSYSTEM=` doesn't help.
* Using the official CPython 3.10 installed via setup-python can also fail: https://github.com/lazka/python-crash-test/actions/runs/5157613189/jobs/9290253297 (with both 2019 and 2022)

## Bisecting:

Testing with official CPython builds:

* NO-ERROR: 3.9.13, 3.10.0-alpha.1, 3.10.0-alpha.2, 3.10.0-alpha.3 <-> 3.11.0-alpha.4, 3.11.0-alpha.5, 3.11.0-alpha.6, 3.11.0-alpha.7, 3.11.3
* ERROR: 3.10.0-alpha.4, 3.10.0-alpha.5, 3.10.0-alpha.7, 3.10.11, 3.11.0-alpha.1, 3.11.0-alpha.3

Error started: [v3.10.0a3...v3.10.0a4](https://github.com/python/cpython/compare/v3.10.0a3...v3.10.0a4)
Fixed: [v3.11.0a3...v3.11.0a4](https://github.com/python/cpython/compare/v3.11.0a3...v3.11.0a4)

Bisect, see next post.

**Comment by lazka** [comment]
Short summary of bisecting the issue with upstream CPython in GHA:

* First bad commit ([v3.10.0a3...v3.10.0a4](https://github.com/python/cpython/compare/v3.10.0a3...v3.10.0a4)): https://github.com/python/cpython/commit/41010184880151d6ae02a226dbacc796e5c90d11
* First fixed commit ([v3.11.0a3...v3.11.0a4](https://github.com/python/cpython/compare/v3.11.0a3...v3.11.0a4)): https://github.com/python/cpython/commit/ed57b36c32e521162dbb97199e64a340d3bff827

**Comment by lazka** [comment]
I've file a bug report: https://github.com/python/cpython/issues/105400 but I don't expect much from it, but who knows.

I'm also not sure how to proceed on the MSYS2 side of things.

**Comment by sskras** [comment]
Wow, impressive. I tried to reproduce this in `cmd` by adding MINGW64 tools to the `PATH` with no success:
![image](https://github.com/msys2/MINGW-packages/assets/7887758/a526e6d8-355b-4f0c-954e-51e59e14be1d)

Did I miss something?

**Comment by Biswa96** [comment]
> Did I miss something?

Yes, this issue does not happen "Locally, outside of CI".

**Comment by eli-schwartz** [comment]
It's a Github Actions runner defined at https://github.com/lazka/python-crash-test/blob/70349faa496cdf19c4bd5152435542542eb7a14f/.github/workflows/main.yml

Logs at https://github.com/lazka/python-crash-test/actions/runs/5190923933/jobs/9358054054

**Comment by sskras** [comment]
@eli-schwartz, sure, I saw the defined action. Well, this says thing about the Guest:
https://github.com/actions/runner-images/releases/tag/win22%2F20230517.1

But no configuration about the lower levels – the VMM/hypervisor, the Host OS/hardware.

**Comment by eli-schwartz** [comment]
I have no idea how people generally find out information about the host hardware and hypervisor used on Github's servers, and would not assume that someone who ran a workflow could find that out.

**Comment by jeremyd2019** [comment]
Interesting that it's specifically `SEM_NOGPFAULTERRORBOX`... the other relevant flag that we are losing by setting `winjitdebug` is `SEM_FAILCRITICALERRORS` and that's the one whose absence results in message boxes for missing exports.  I don't know if there's a reasonable way to only set one and not the other for child processes though, as a workaround to keep CI from hanging on missing exports while still working around this issue.  It's probably not worth a new MSYS option and additional patching of msys2-runtime over...

**Comment by kasper93** [comment]
Small update. I've reviewed meson's `symbolextractor.py` code. While there are few things that could be improved, it is not related to this issue.

One important thing I noticed that the issue happens only with `llvm-nm` which is preferred by meson, it does not happen with mingw's `nm`.

I think next step would be to remove meson and ninja (if possible) from the reproducer. I tested with script that only runs `llvm-nm` on the library. The reproducer is pretty minimal, good job on that, but removing components like meson would really help to focus on important parts.

But my fear is that since it doesn't happen with Python 3.11 there will not be much interest (if at all) to find the root cause of this.  I think during process exit some resources/fd are not in a valid state which causes the issue.

**Comment by anarazel** [comment]
> Interesting that it's specifically SEM_NOGPFAULTERRORBOX...

There's a lot tied into that one these days... Windows error reporting, JIT debugging, etc only happen when SEM_NOGPFAULTERRORBOX is *not* set.


> I don't know if there's a reasonable way to only set one and not the other for child processes though

I hit this issue without mingw or llvm-nm being involved (meson running C binaries compiled with msvc, via msbuild, not ninja). SEM_NOGPFAULTERRORBOX was the relevant factor, SEM_FAILCRITICALERRORS did not matter.  Unfortunately the failure rates in my case are too low to make for good test case, and I hadn't been able to increase them meaningfully.

From writing this up for postgres:
> The problem:
>
> Occasionally ecpg test files would fail to compile, exiting with -1073741819:
> C:\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\cirrus\build\meson-private\custom_target.rule' exited with code -1073741819. [c:\cirrus\build\src\interfaces\ecpg\test\sql\3701597@@twophase(dot)c(at)cus(dot)vcxproj]
>
> -1073741819 is 0xc0000005, which in turn is STATUS_ACCESS_VIOLATION, i.e. a
segfault. This happens in roughly 1/3 of the builds, but with "streaks" of not
happening and more frequently happening.
>...
> The problem even persisted when replacing meson's sys.exit() with os._exit(),
which indeed just calls _exit().

Which to me strongly hints that the issue is somewhere in the windows runtime.  

Possibly the explanation for why the issue is visible in CI but not, so far, locally, is due to different version of the windows runtime being used.

**Comment by kasper93** [comment]
Would it be possible to update Python package to 3.11? It is already at 3.11.4 and 3.10 is in "security fixes" only stage. Arch also provides 3.11 by default, but of course they have also other version available in repo.

**Comment by lazka** [comment]
I can confirm that a mingw build of 3.11 also doesn't crash: https://github.com/msys2-contrib/cpython-mingw/pull/139#issuecomment-1605917011

**Comment by Biswa96** [comment]
Should this be closed?

**Comment by lazka** [comment]
Let's hope it doesn't come back :)
