### ISSUE TITLE
[zimg] library does not export any symbols in clang32 and clang64

### ISSUE THREAD

**Issue by kasper93** [msys2/MINGW-packages#17834]
### Description / Steps to reproduce the issue

After recent zimg update https://github.com/msys2/MINGW-packages/commit/ecfbbb23fb74432a1dffe327bd607edaae1d7ac6 it cannot be linked with clang32/clang64, works ok with others. (not tested on arm)

``` c
#include <stdio.h>
#include <zimg.h>

int main() {
    unsigned major, minor, micro;
    zimg_get_version_info(&major, &minor, &micro);
    printf("%u.%u.%u\n", major, minor, micro);
}
```

```
$ cc main.c `pkgconf --libs --cflags zimg` && ./a.exe
ld.lld: error: undefined symbol: zimg_get_version_info
```

It is recent regression, that broke mpv CI, example jobs:
https://github.com/mpv-player/mpv/actions/runs/5625603840/job/15244725573
https://github.com/mpv-player/mpv/actions/runs/5625603840/job/15244725732
As we can see only clang/lld builds are affected.

### Expected behavior

zimg can be linked

### Actual behavior

zimg cannot be linked

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22000

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Hi @kasper93, Thank you for reporting the issue. I have added a pull request to fix this issue. Would you like to test the packages from GitHub Actions artifacts of that pull request?

The issue is more severe than the original post. The zimg shared library compiled with clang does not export any symbols. But the gcc compiled zimg library exports _all_ the private & public symbols. The issue has been mitigated by using the DEF file with `-export-symbols` libtool flag.

**Comment by kasper93** [comment]
Thanks, works correctly now.

**Comment by Biswa96** [comment]
The patch has been added in this pull request https://github.com/sekrit-twc/zimg/pull/200
