### ISSUE TITLE
Weird error with fltk

### ISSUE THREAD

**Issue by Aeeeee-the-Sassy** [msys2/MINGW-packages#17849]
I've tried to compile a c++ file with FLTK library linked and cstdlib included:
g++ -o main main.cpp `/mingw64/bin/fltk-config  --cxxflags --ldflags --use-images`

And it gave me this error:
In file included from main.cpp:1:
C:/msys64/ucrt64/include/c++/13.1.0/cstdlib:141:11: error: 'at_quick_exit' has not been declared in '::'
  141 |   using ::at_quick_exit;
      |           ^~~~~~~~~~~~~
C:/msys64/ucrt64/include/c++/13.1.0/cstdlib:164:11: error: 'quick_exit' has not been declared in '::'
  164 |   using ::quick_exit;
      |           ^~~~~~~~~~

Removing either cstdlib or fltk makes the compilation go as usual.
(I've also tried to compile the same file on linux and it worked perfectly, so that's clearly an msys2 error).

**Comment by adalisk-emikhaylov** [comment]
You're mixing MINGW64 and UCRT64 [environments](https://www.msys2.org/docs/environments/). Having to manually specify the path to `/mingw64/bin/fltk-config` is a sign of that. `fltk-config` should already be in the PATH, assuming you start MSYS2 shell for the correct environment (MINGW64). Or, if you want to keep using UCRT64, you need to install `mingw-w64-ucrt-x86_64-fltk` instead of `mingw-w64-x86_64-fltk`.
