### ISSUE TITLE
mingw-w64-gcc update to 13.2

### ISSUE THREAD

**Issue by JaiSoone** [msys2/MINGW-packages#17887]
### Package name

mingw-w64-gcc

### New version number

13.2

**Comment by tenko** [comment]
Can we now activate Modula-2 language in the build?
> --enable-languages=m2  ...

**Comment by lazka** [comment]
> Can we now activate Modula-2 language in the build?

What do you need it for?

**Comment by tenko** [comment]
I was thinking to use it for embedded development.

Due to the restricted nature of the language, a lot of static
checks are possible and also many runtime check available,
making it a good fit for this purpose. It has many of the
characteristics of Ada, but is much simpler.

It also has a very large test suite of some 12 000 tests and is
a bootstrapped compiler, ensuring quality.

Link : https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gm2/Why-use-GNU-Modula-2.html

I was able to build it one year ago by editing out some POSIX
parts (e.g. termcap) and dated API, but it failed in the last link stage:

Link : https://lists.gnu.org/archive/html/gm2/2022-10/msg00012.html

I saw on the mailing list , a similar bug was fixed for Mac platform and
was thinking now it should be possible to build:

Link : https://lists.gnu.org/archive/html/gm2/2022-12/msg00018.html

Gaius Mulley, who is lead on the project is very helpful and would
probably be very interested in getting this to run on the Windows
platform as this exposes many hidden problems.
