### ISSUE TITLE
[boost] boost::container::flat_map iterator has different behavior depending on compiler optimization flags with gcc

### ISSUE THREAD

**Issue by prus1337** [msys2/MINGW-packages#17977]
### Description / Steps to reproduce the issue

g++ v13.1.0, boost v1.82
The following example has different behavior depending on compiler optimization flags:
```C++
#include <boost/container/flat_map.hpp>

#include <cstdint>
#include <iostream>
#include <string>

int main()
{
    boost::container::flat_map<std::string, size_t> map{};
    const std::string key = "test";
    const size_t value = 13;
	
    auto [it, succeeded] = map.emplace(key, value);
	
    if (succeeded)
    {
        std::cout << "emplace result: " << it->first << " -> " << it->second << "\n";
        std::cout << "emplace iterator result: " << "it == map.end() is " << std::boolalpha << (it == map.end()) << "\n";
		
        it = map.find(key);
        std::cout << "find result: " << it->first << " -> " << it->second << "\n";
        std::cout << "find iterator result: " << "it == map.end() is " << std::boolalpha << (it == map.end()) << "\n"; 
    }
	
    return 0;
}
```

### Expected behavior

Without optimization flags (-O0, -O1) everything fine.
g++ -O0 -o boost_v1.82_flat_map_it_bug boost_v1.82_flat_map_it_bug.cpp

> $ ./boost_v1.82_flat_map_it_bug
emplace result: test -> 13
emplace iterator result: it == map.end() is false
find result: test -> 13
find iterator result: it == map.end() is false

### Actual behavior

With optimization flags (-O2, -O3) iterator has bad value.
g++ -O2 -o boost_v1.82_flat_map_it_bug boost_v1.82_flat_map_it_bug.cpp

>  ./boost_v1.82_flat_map_it_bug
emplace result: test -> 13
emplace iterator result: it == map.end() is true
find result: test -> 13
find iterator result: it == map.end() is true

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

**Comment by Biswa96** [comment]
Thank you for reporting the issue. Though the latest version of gcc is 13.2.0, I can reproduce the issue with that in my system.

The issue does not happen in Linux with gcc 13.2.1 toolchain.

**Comment by prus1337** [comment]
> Thank you for reporting the issue. Though the latest version of gcc is 13.2.0, I can reproduce the issue with that in my system.
> 
I have updated the compiler and this problem is also reproduced on gcc 13.2.0.
> The issue does not happen in Linux with gcc 13.2.1 toolchain.

Yes. This problem does not reproduce on Linux.

**Comment by lhmouse** [comment]
The issue is caused by https://github.com/boostorg/container/blob/b8b089730ad7a9cd4a97f5796827177475462d0c/include/boost/container/flat_map.hpp#L69-L75

which is
```c++
template<class D, class S>
BOOST_CONTAINER_FORCEINLINE static D force_copy(const S &s)
{
   const D *const vp = move_detail::force_ptr<const D *>(&s);
   D ret_val(*vp);
   return ret_val;
}
```
almost equivalent to
```c++
template<class D, class S>
BOOST_CONTAINER_FORCEINLINE static D force_copy(const S &s)
{
   const D *const vp = reinterpret_cast<const D *>(&s);
   D ret_val(*vp);
   return ret_val;
}
```
and violates strict-aliasing rule. The code effects undefined behavior. Adding `-fno-strict-aliasing` when invoking GCC will avoid the issue.

**Comment by lhmouse** [comment]
In order to simplify the testcase, this program is used
```c++
int main() {
  boost::container::flat_map<int, int> map;
  auto it = map.emplace(123, 456).first;
  printf("key = %d, value = %d, end = %d\n", it->first, it->second, it == map.end());
}
```
which is pre-processed and fed into _creduce_, checking that it ourputs `key = 123, value = 456, end = 0` with `-O1` and `key = 123, value = 456, end = 1` with `-O2`.

creduce is fxxking terribly slow on Windows and takes hours to run, so please wait patiently.

**Comment by lhmouse** [comment]
Okay creduce on Windows is unbearably slow. I copied the partially reduced source to a Linux machine. The definition of `size_t` had to be fixed, and an implementation of `_assert()` had to be added; nevertheless, it allowed the reduction to run much faster. Here is the result of _cvise_. It's very long and complex, but cvise cannot make any progress.

[test.cc.txt](https://github.com/msys2/MINGW-packages/files/12289905/test.cc.txt)

Apparently boost has their own `pair` and they attempt to reinterpret iterators to their `pair` as iterators to `std::pair`. That's why it's undefined behavior.

This issue is not specific to Windows, and not specific to GCC 13. GCC 12 is also affected, but GCC 11 is immune.
