### ISSUE TITLE
[mypaint] After installing can't launch mypaint

### ISSUE THREAD

**Issue by aandrejevas** [msys2/MINGW-packages#20787]
### Description / Steps to reproduce the issue

1. pacman -S mingw-w64-ucrt-x86_64-mypaint
2. open UCRT64 environment
3. launch mypaint
4. An error is printed to console. Brushes are not found because of a path issue it seems.

### Expected behavior

mypaint would launch successfully.

### Actual behavior

![image](https://github.com/msys2/MINGW-packages/assets/53169542/176d0c35-7564-42dc-b73a-fa0576a943e2)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix this issue. It happens because the `$MINGW_PREFIX/lib/mypaint/lib/config.py` file contains the build directory from CI as following.

```
mypaint_brushdir = u'D:/a/msys64/ucrt64/share/mypaint-data/2.0/brushes'
```

This is fixed by changing that path to current installation directory after installing the mypaint package. The issue should be fixed by mypaint package version 2.0.1-5.
