### ISSUE TITLE
[box2d] Update to version 3.0

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#22082]
### Description / Steps to reproduce the issue

Please, update package to latest version 3.0.

### Expected behavior

Package updated.

### Actual behavior

Package is not updated.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Version 10.0.22631 Build 22631

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] #22085
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

**Comment by felixaszx** [comment]
It might not be a good idea to update this package instead of having 2 versions of it avaliable. According to this [article](https://github.com/erincatto/box2d/blob/main/docs/migration.md) by the box2d team, apis of the library has been move from C++ to C. Which might break existing projects that required it.

**Comment by felixaszx** [comment]
I think this can be closed now, since I have already updated the package to 3.0.
