### ISSUE TITLE
g++ cannot find crc32_combine in cc1plus.exe in the gcc (14.2.0) package for both UCRT64 and MINGW64

### ISSUE THREAD

**Issue by Plasma3** [msys2/MINGW-packages#22773]
### Description / Steps to reproduce the issue

I downloaded the gcc package for the UCRT64 enviroment (`mingw-w64-ucrt-x86_64-gcc 14.2.0-2`) and added "C:\msys64\ucrt64\bin" to my PATH. The `gcc` command works fine but `g++` (example `g++ main.cc`) gives me the following popup when I'm trying to run it:
![bild](https://github.com/user-attachments/assets/7b2c9404-4a15-45f5-bec6-f1068fce1013)
(Translate: cc1plus.exe - Unable to find start address   Cannot find the procedure start address for crc32_combine in the DLL file C:\msys64\ucrt64\bin\..\lib\gcc\x86_64-w64-mingw32\14.2.0\cc1plus.exe.)

Tried the same but with MINGW64 instead (`mingw-w64-x86_64-gcc 14.2.0-2` and switched PATH to "C:\msys64\mingw64\bin") and it gives me the same error.

My current workaround was to download `gcc 13.3.0-1` for the MSYS enviroment and switching PATH to "C:\msys64\usr\bin".

## Steps
1. Install msys2
2. Install `mingw-w64-ucrt-x86_64-gcc` or `mingw-w64-x86_64-gcc`
3. Add "C:\msys64\ucrt64\bin" or "C:\msys64\mingw64\bin" to PATH
4. Run `g++ main.cc` (where main.cc is a C++ program that should compile, a simple "Hello World" does it)

### Expected behavior

g++ compiles the program correctly or prints out compile errors/warnings

### Actual behavior

g++ crashes with the following popup:
![bild](https://github.com/user-attachments/assets/367db119-ea84-48c1-b665-623a6001872a)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

**Comment by Biswa96** [comment]
I can not reproduce the issue. Please check if antivirus programs are not interfering with the process.

**Comment by xiaoaiwhc** [comment]
Using x64Dbg to attach the cc1plus.exe and then open the Log Windows of x64Dbg, check all DLLs which are from the Windows System dictionary, there must be some conflicts with your MSYS64's one. For me, the zlib1.dll which is located at C:\Windows\System32 conflicts with the MSYS64's one.

**Comment by mas-co** [comment]
I stumbled across this thread after running into this issue after a long-overdue pacman update to my MSYS2 installation on my PCs.  g++ worked fine on my workstation, but not on my laptop.  Ater a little poking around I believe that the problem is a conflict with the Intel "PROSet/Wireless Software" that accompanies the Intel drivers.  (My laptop uses the Intel Wireless-AC 9560 RF module).

There are versions of Intel's wifi drivers that do not include this additional software, the so-called "Drivers for IT Administrators".  After uninstalling the PROSet/Wireless software I installed the wifi drivers from: 
[ https://www.intel.com/content/www/us/en/download/18231/intel-proset-wireless-software-and-wi-fi-drivers-for-it-administrators.html
]( https://www.intel.com/content/www/us/en/download/18231/intel-proset-wireless-software-and-wi-fi-drivers-for-it-administrators.html
)

I hope this helps anyone that stumbles across this.
