### ISSUE TITLE
Build LLDB with Python (Scripting) support

### ISSUE THREAD

**Issue by jhasse** [msys2/MINGW-packages#3222]
Required for https://github.com/vadimcn/vscode-lldb/issues/37 for example.

**Comment by revelator** [comment]
Unfortunatly it expects windows python and not mingw64 python, i been trying for some time to get it to accept the mingw64 python but so far no success. Needs a lot of hacking about in the cmake files i suspect.

**Comment by Alexpux** [comment]
I think can be used cmake official FindPython aor custom FindPython module from some of projects. Our python is widely used when building with cmake

**Comment by mewmew** [comment]
@Alexpux do you know where to make the necessary changes? It would be great to see Python support in lldb enabled.

Cheers,
/u

**Comment by mewmew** [comment]
@revelator With release 6.0, do you know if there is better support for Python that could help this issue?

**Comment by revelator** [comment]
Been bedwritten after major backsurgery so i havent had the time to look at it yet, but i suspect that it might still need windows python. Since the mingw64 python seems to be following the same layout as the posix version it might be possible to adjust the cmake files so that when the build chain detects MINGW* it will use this layout. 
Ill have a look at it soon.

**Comment by Alexpux** [comment]
I’m already do everything. Need just fix symbols visibility when building SWIG wrapper

**Comment by revelator** [comment]
Thanks, things are more or less back to normal, still getting a bit tired when up for more than a few hours but getting better by the day. Looks like Alex allready fixed up most of the problems like he mentioned above :), swig integration would be a nice next step.
