### ISSUE TITLE
Change the CI: Abstruse CI

### ISSUE THREAD

**Issue by walker27460** [msys2/MINGW-packages#3445]
How about to change the Continuous Integration Service to Abstruse CI?
It's Docker-based and can deploy on Windows PC.

**Comment by lazka** [comment]
Why? And how does it compare to appveyor for example?

**Comment by yuui-tanabe** [comment]
because Tea CI is Wine based and I heard Wine don't support recent MSYS2.

**Comment by emmenlau** [comment]
I could not find any information that Abstruce would support Windows-in-Docker. It seems an interesting CI system, but can you please point to some information how Windows containers work and what OS are supported etc?
Docker has some support for Windows Server in a docker container when running Docker for Windows on Windows Server 2016 or Windows 10. AFAIK thats the only supported setup? Can you elaborate?

**Comment by mati865** [comment]
Few quick explanations to some questions in this thread:
- Docker on Windows 10 is just a virtual machine opposed to lightweight Linux containers.
- Abstruse CI is a service that you host yourself on your server.
- MSYS2 needs native Windows environment because Cygwin doesn't work with Wine anymore.

I don't see how MSYS2 could use Abstruse CI.

**Comment by peterbud** [comment]
@mati865 can you elaborate on this comment:

> Docker on Windows 10 is just a virtual machine opposed to lightweight Linux containers

**Comment by mati865** [comment]
@peterbud you can see this article https://sreeninet.wordpress.com/2017/05/13/docker-for-windows-different-modes/

**Comment by peterbud** [comment]
As I read the article you have mentioned, and also the [documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10) plus based on my experience docker is using native windows containers, and no VM is needed to run your containers.

**Comment by filipesilva** [comment]
I came across this issue while looking trying to get msys working on docker containers. In my case I am using https://www.buildkite.com/ but the idea seems similar to https://abstruse.bleenco.io/.

I can confirm that you can run MSYS2 in a Windows container, but there are a couple of caveats:
- the `microsoft/windowsservercore` base image must be used instead of `nanoserver` (https://github.com/Alexpux/MSYS2-packages/issues/1493)
- output doesn't show on tty console (https://github.com/docker/for-win/issues/262, https://github.com/Alexpux/MSYS2-packages/issues/1490)
- MSYS2 binaries will crash the container unless all MSYS dlls are touched when when running the container (https://github.com/docker/for-win/issues/2920)

Keeping those things in mind, it works. I'm currently setting it up in this https://github.com/angular/angular/pull/27205. In that PR you can find the host provisioning script and the docker image. I'm using Google Cloud Platform for the hosts, but I think you can use whatever you want.

**Comment by umarcor** [comment]
Is this still relevant now, given that GitHub Actions are used?
