### ISSUE TITLE
sys/ioctl.h: No such file or directory

### ISSUE THREAD

**Issue by billskeen68** [msys2/MINGW-packages#3798]
I think this is an issue with the avs sdk build and not mingw64, but posting here just in case.

Getting the following error:

src/hostapi/oss/pa_unix_oss.c:54:10: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:227: src/hostapi/oss/pa_unix_oss.lo] Error 1

**Comment by StarWolf3000** [comment]
This file is not available for MSYS2 and most likely Cygwin. It provides **device-specific low-level control of devices** abstracted behind a file-based interface on a POSIX-based operating system. This works different in how it will on a Windows system.
I doubt Cygwin is able to provide a compatibility layer for this, since you not only need the header, but also an implementation of the functionality itself, and thats the point were it will most likely fail, because it needs to operate on low-level.

The Windows implementation is described in [this MSDN article](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363219(v=vs.85).aspx)

**Comment by cbrt64** [comment]
I don't know anything about this specifically, but `/usr/include/sys/ioctl.h` is found in the msys2-runtime-devel package, and `/usr/bin/msys-2.0.dll` does implement and export Cygwin's `ioctl()`. It is thus available to binaries built with msys2 gcc, though presumably not usable by mingw64 gcc.

For future reference, a file's owning package can be found by doing e.g. `pacman -Fys ioctl.h`.

**Comment by MehdiChinoune** [comment]
see above https://github.com/msys2/MINGW-packages/issues/3798#issuecomment-391952666
