### ISSUE TITLE
Improve Qt-packaging (or general packaging guidelines)

### ISSUE THREAD

**Issue by sgsaenger** [msys2/MINGW-packages#4056]
As it is, the qt5 package is more than overkill for most applications.
Where on arch, a simple qbs-based project needs three packages (qt5-base, qt5-script, qbs)
that total ~70mb, here simply wanting to use qbs amounts to 7gb.

I've read #3928, but this does not really solve the issue.
Even when you don't intend to run multiple builds, there should be no problem in simply creating multiple packages from one PKGBUILD, and creating metapackages that allow installation of a complete Qt5 suite, if one really wants to.

For both CI as well as end-user needs, a simple qt5-base package could solve most dependencies, both for creating/building own software, as well as for other software from your repository, with the possibility to pull in qt-extensions as needed. Devel packages could then be only installed, when using Qt for own development issues, with no more effort for the user as it is now.

**Comment by Alexpux** [comment]
@sgsaenger you can submit pull request and we will review it. Don't forget that after every subpackage install you need run qtbinpatcher

**Comment by zgyarmati** [comment]
This issue hits me as well, and I'm considering to work on this, but given the fact that it's a significant amount of work, before i start i would like to confirm that once it's done and works properly, it will be merged into the mainline repository, hence I request for comments here.

 My conception is to have separated packages for each Qt source submodule (so like mingw-w64-{qt5base,qt5serialport,qt5tools} etc, see the full list of submodules at https://download.qt.io/archive/qt/5.12/5.12.2/submodules/), and after everything is in place, the existing mingw-w64-qt5 package would be would be only a metapackage, which pulls in all of the sub-packages. This packages would build separately from the linked submodule source tarballs. This is how it's done for example in MXE (see
https://github.com/mxe/mxe/blob/master/src/qtbase.mk  and the other qt*.mk files)

 The other solution would be to build from the unified tarball (qt-everywhere-src-5.12.2.tar.xz) everything (as it is happening now), and split the package into pieces. This would solve the problem from the user point's of view (as she would be able to install only the components actually needed), but wouldn't solve the problem of the maintainers (that is: it's a huge PITA to work with the package due to the long building times).

@Alexpux , what do you think?

**Comment by Optiligence** [comment]
ref #6141
