### ISSUE TITLE
mingw-w64-portaudio issue

### ISSUE THREAD

**Issue by aquilarubra** [msys2/MINGW-packages#4705]
Hi, I tried to compile mingw-w64-portaudio on two machines, using recently installed and update msys2 and mingw.

I get this error during make:
x86_64-w64-mingw32-gcc.exe: fatal error: no input files

As I understand, it happens after each long command line. I found a post where they were saying that Windows has a limit in the number of characters allowable in the command line.

When I add asio to the package, the command string gets bigger and I find even more of those errors.

Am I missing something or is there any fix to make it work?

**Comment by revelator** [comment]
allways try to build with the shortest PATH avaliable.
with makepkg-mingw do something like this -> BUILDDIR=/D makepkg-mingw (flags)
this will build everything directly in the root of the drive, and no you will not have a mess of the sources scattered around on your drive afterwards since the buildsystem creates a folder with the same name as the project in the root of the drive, where it then builds it. you can also use subst to create a virtual drive linking to the BUILDDIR if you dont trust that it will do as i said, but it will :)

**Comment by Biswa96** [comment]
This issue seem to be solved and can not be reproduced.
