### ISSUE TITLE
qt5-static  _with_icu=no

### ISSUE THREAD

**Issue by tim-lebedkov** [msys2/MINGW-packages#4884]
ICU adds about 30 MB to the newly built executables with qt5-static. As one of the reasons for static builds is to reduce the size, I would suggest to set  _with_icu by default to "no".

**Comment by Optiligence** [comment]
there is a reason this got added, it’s just missing functionality when omitted
ref https://github.com/Alexpux/MINGW-packages/pull/4587#issuecomment-435357110

i haven’t heard of static builds being used for small executable sizes yet…

@Alexpux please don’t just remove functionality

if you really want to, you can check out and try to fix https://github.com/Alexpux/MINGW-packages/issues/1999 
(i.e. stripping release executables has an effect because they contain bloat)

**Comment by Alexpux** [comment]
@Optiligence, I use Qt5 static for a years without ICU. I really don’t want to increase executable in 4-5 sizes. You can always build your own custom Qt5 static, but in MSYS2 repo I will not produce Qt5 static with ICU anymore

**Comment by Optiligence** [comment]
@Alexpux I it’s about feature parity with the dynamic builds and the official releases. (which should be the default, i believe)
I certainly don’t want to maintain a separate repository just to get that. 

I had bugs because of this. Like some xml files from external sources not opening with the release builds, that worked fine during development and on any other platform. Those were not easy to track down. 

And yes, `libicudt62.dll` is 25,6 MiB in size, something you’d have to ship for the shared build too.

**Comment by Alexpux** [comment]
I’m also don’t want to maintain what I don’t want. So I will distribute Qt5-static builded without ICU
