### ISSUE TITLE
argon2 library is now broken

### ISSUE THREAD

**Issue by droidmonkey** [msys2/MINGW-packages#4921]
PR #4817 has broken the symbol table for the libargon2.a output. This is impacting the KeePassXC project who originally proposed inclusion of Argon2 in MSYS.

These are the lines that _I believe_ are to blame:
https://github.com/Alexpux/MINGW-packages/blob/58bdd5d5500547b12b757defe55b38a2a18ac10e/mingw-w64-argon2/002-mingw-fix-src.patch#L72-L74

@JPeterMugaas can you explain your rational behind all the changes you made in your PR? For now I am manually reverting back to the -2 version of this package.

See https://github.com/keepassxreboot/keepassxc/issues/2654 for background.

**Comment by droidmonkey** [comment]
I have confirmed that removing the lines referenced from the patch file fixes the issue we are experiencing. __declspec(dllexport) is MSVC option (ie, dll) and not appropriate for archive libraries.

https://docs.microsoft.com/en-us/cpp/cpp/declspec?view=vs-2017

**Comment by JPeterMugaas** [comment]
I originally put those two lines in because I was worried about exporting functions for the .DLL and I wanted to be consistent with what was being done for MSVC.  I thought argon.h was being used by some units in the argon library itself and thus, I thought that the functions should be exported for the DLL.  https://docs.microsoft.com/en-us/cpp/build/importing-into-an-application-using-declspec-dllimport?view=vs-2017 .  I might be missing something in the source-code or some detail in the Makefile.

I have gone ahead and removed the lines as suggested and I made an update PR at https://github.com/Alexpux/MINGW-packages/pull/4922 .  This includes both the mingw-w64-argon2 and mingw-w64-python-argon2-cffi packages since they use the same exact patch file.  I like to keep 002-mingw-fix-src.patch the same between both to kill two birds with one stone (forgive my idioms).

**Comment by droidmonkey** [comment]
Your new commits fix the issue for me
