### ISSUE TITLE
doxygen: Segmentation fault

### ISSUE THREAD

**Issue by peterbud** [msys2/MINGW-packages#4959]
With the latest change #4858 doxygen canoot build the documents for libgphoto2:
```
doxygen Doxyfile
Notice: Output directory `doxygen-output' does not exist. I have created it for you.
Searching for include files...
Searching for example files...
....
Generating SQLITE3 output...
Initializing DB schema (tables)...
Generating Sqlite3 output for class @0
Generating Sqlite3 output for class @2
Generating Sqlite3 output for class @3
Generating Sqlite3 output for class _Camera
Generating Sqlite3 output for class _CameraAbilitiesList
Generating Sqlite3 output for class _CameraFile
Generating Sqlite3 output for class _CameraFileHandler
....
Generating Sqlite3 output for class _CameraFilesystemFolder
Generating Sqlite3 output for class _CameraFilesysmake[3]: *** [Makefile:863: libgphoto2-api.html.stamp] Segmentation fault

```
After reverting back to doxygen `1.8.14-3` the build is successful.

**Comment by Alexpux** [comment]
Well I dont have time and with to dig into doxygen

**Comment by peterbud** [comment]
I understand that. 
@JPeterMugaas as you made the last changes?

**Comment by JPeterMugaas** [comment]
I'm looking now but I don't personally have a clue.  That's why I haven't responded.  I have attempted building libgphoto 2.5.22 but the problem persists there.  That might worth updating anyway but that's a separate matter.

I tried the msys doxygen "doxygen-segfault.patch" file but that patch is in the source-code for 1.8.15 so I don't think that omission is an issue.  It probably should've been dropped for the MSYS version as well as the MINGW version.

Right now, I am looking at some patches from CygWin so keep your fingers crossed.

**Comment by JPeterMugaas** [comment]
Alright, I have tried building with the cygwin patches but I don't think that solves the problem with Doxygen and libgphoto although it might address other issues.  It was worth a shot.

**Comment by revelator** [comment]
Also fails with daala-git.

**Comment by lazka** [comment]
libgphoto2-2.5.21 builds fine now with the latest doxygen package. Could it be that this is fixed?

**Comment by peterbud** [comment]
thanks @lazka , indeed it does work now, I have tried the 2.5.23, after removing the doxygen patches, I have managed to compile it without segfault.
