### ISSUE TITLE
Possible issues building Emacs with GCC-8.3

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#5284]
Recently I have found issue building Emacs from master and Ive flagged them to [Emacs mailing list](http://lists.gnu.org/archive/html/emacs-devel/2019-04/msg01152.html). maybe you are interested too...

**Comment by oscarfv** [comment]
The likely problem was traced to a change on Emacs that triggered a bug on gcc. A workaround was implemented in Emacs.

BTW, the problem is in the development version, not on any released version. One Emacs contributor thought that flagging some functions with `__attribute__ ((cold))` would be good for performance, but this causes a crash with `-O2` on MinGW. So Emacs does not use that attribute on MinGW anymore.

Angelo, please close this issue. Thanks.
