### ISSUE TITLE
All executable files in `msys64\mingw32\lib\gcc\i686-w64-mingw32\7.4.0` launch fail

### ISSUE THREAD

**Issue by tan-wei** [msys2/MINGW-packages#5344]
It is quite weired that all executable files under `msys64\mingw32\lib\gcc\i686-w64-mingw32\7.4.0` crash when executed.
For example, `cc1plus.exe` wil crash after executed, 
![图片](https://user-images.githubusercontent.com/28227509/57576881-59652880-749d-11e9-93c9-32889bcfb910.png)
Error number is 0xc000007b, I searched in google, it seems that some incompatible DLLs are loaded will raise this exception. So how can I do to solve this?
The latest version of MSYS2 and gcc which is installed by pacman. Thanks!

**Comment by oscarfv** [comment]
Those executables depend on dlls placed on msys??/mingw32/bin. Therefore, if you execute those programs without that directory on PATH environment variable they will abort in the way you are observing.

If you execute them from a MINGW32 shell, do they crash? The MINGW32 shell puts the required directories in PATH environment variable.

Please close this issue if your problem is solved. Thanks.

**Comment by tan-wei** [comment]
Got it. After I add `msys??/mingw32/bin` in PATH, it works. So the issue can be closed. Thanks for your kind replying.

But the way, where can I open the issues about the compiler itself? Here or somewhere else?

**Comment by oscarfv** [comment]
The compiler's project page is http://gcc.gnu.org There is a link to their bug reporting system there.

You can report bugs here when you suspect that the problem is related to Windows, MSYS2 or the MinGW runtime.

By the way, the executables in mingw32/lib/... are not supposed to be directly invoked by the user. It is normal that you encounter problems if you try to use them.

**Comment by tan-wei** [comment]
@oscarfv Thanks for your reply.
Just because I use MinGW outside `MSYS`, I use VSCode with CMake to build everything. Building steps are successful, however,  I use `cquery` to parse the source codes, it seems that cquery directly call `cc1plus.exe` and crash, so I find that we can't directly run them. With your help, I can add something into PATH to avoid the crashing.

I try to build a project named `taocpp/json`, `MinGW 7.4`, `GCC-linux`, `Clang-MSVC` all work well. However, `MinGW 8.3` will fail at the end of the linking step, it takes over 3 hours linking but still not finished. I think I should raise a issue to [](http://gcc.gnu.org ).

Anyway, thanks very much.

**Comment by tan-wei** [comment]
@oscarfv One more question about environment. If I add `msys??/mingw32/bin` and etc. in `PATH`, is it a wise choice for me if I use MinGW out of `bash`?
Why I ask this question? I remember I see it is not recommended adding some paths in `PATH` somewhere (maybe from `cygwin`, may be somewhere else). But I do not see descriptions around website and wiki of `MSYS2`.
Thanks very much!

**Comment by oscarfv** [comment]
If you start MSYS2 bash with the correct shortcut (MINGW32 for working with 32 bit Mingw-w64 toolset, etc) you don't need to add any other directory to PATH.

The problem with adding other directories to PATH is that some of those external applications might come with its own version of MSYS2 or Cygwin and this can cause problems because  the executables might pick the wrong dlls. That's not the case of mingw??/bin directories that MSYS2 creates, they are safe to mix with /msys??/bin. In fact, you should put them before /msys??/bin, but if you start bash with the correct shortcut that will be done autmatically.

I recommend reading https://github.com/msys2/msys2/wiki for learning what MSYS2 is/isn't and how to use it properly.

If your doubts are resolved, please close this issue. Thanks.
