### ISSUE TITLE
codelite-git fails to build

### ISSUE THREAD

**Issue by stahta01** [msys2/MINGW-packages#5371]
I am working on getting codelite-git to build. I have about 4 hours of work done.
I hope to have it fixed by this time tomorrow.

Edit: At around the 75% build I am having linking errors; I hope there is not very many of them.
It takes a lot of time to build using make -j1 which is needed to get meaningful errors.

Tim S.

**Comment by oscarfv** [comment]
If you use ninja instead of make you can get sane error output, parallel build and on top of it even a bit of an speedup.

In `PKGBUILD` replace `-G"MSYS Makefiles" \` with `-G Ninja \` and, a bit below, `make` with `ninja`. Of course, you also need `${MINGW_PACKAGE_PREFIX}-ninja` as a build dependence.

**Comment by stahta01** [comment]
Thanks for the cmake/ninja info. I have almost gotten it done. So, will not try it for this project.
Tim S.

**Comment by stahta01** [comment]
#5381 PR submitted
