### ISSUE TITLE
Rsvg using from Python3 is broken

### ISSUE THREAD

**Issue by gbtami** [msys2/MINGW-packages#5622]
```
Traceback (most recent call last):
  File "setup.py", line 147, in <module>
    exec(open("create_theme_preview.py").read())
  File "<string>", line 35, in <module>
  File "lib/pychess\gfx\Pieces.py", line 164, in set_piece_theme
    svg_pieces = get_svg_pieces(piece_set)
  File "lib/pychess\gfx\Pieces.py", line 106, in get_svg_pieces
    "pieces/%s/%s.svg" % (svgdir, svgdir)))
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
```
Referenced line is using Rsvg.Handle.new_from_file(). It worked OK from long years without any problem.
I'v noticed that librsvg-2-2.dll file size increased a lot compared to older (working OK) versions.

**Comment by mati865** [comment]
It was updated to latest version: https://github.com/msys2/MINGW-packages/commit/c896f49d0b54bb9b22203d91f692c5d9f2725159#diff-4e545bc4881d23f7fe4cf120f4bafab4

Seems to be fixed in testing 2.45 branch: https://gitlab.gnome.org/GNOME/librsvg/commit/ed942ce0ff98e579e155b2e1621de683942b6f0c
Probably backporting this commit should be enough.

**Comment by lazka** [comment]
I've asked for a backport: https://gitlab.gnome.org/GNOME/librsvg/issues/426#note_561714

**Comment by federicomenaquintero** [comment]
What are the contents of the problematic string being passed to `rsvg_handle_new_from_file()`?

I'm asking because as far as I can remember from the history of https://gitlab.gnome.org/GNOME/librsvg/issues/426, the bug only occurred in the 2.45 series, not in 2.44.  In 2.44, the code is different from the 2.40 series that mingw had previously, but I hadn't heard of this sort of problem in that branch.

**Comment by lazka** [comment]
> What are the contents of the problematic string being passed to `rsvg_handle_new_from_file()`?

I get `Operation not supported (15)` with absolute paths: ` Rsvg.Handle.new_from_file("C:/foo")`

**Comment by gbtami** [comment]
In my case the contents of the problematic string being passed to rsvg_handle_new_from_file() is
C:\msys64\home\tamas\pychess\pieces\celtic\celtic.svg

**Comment by federicomenaquintero** [comment]
Thanks! I posted a link to a test branch in [the original bug](https://gitlab.gnome.org/GNOME/librsvg/issues/426#note_563548). Could you please test https://gitlab.gnome.org/federico/librsvg/commits/windows-new-from-file ?

**Comment by lazka** [comment]
>  Could you please test https://gitlab.gnome.org/federico/librsvg/commits/windows-new-from-file ?

No change with the last commit backported, but maybe this helps explain why:

```python
>>> from gi.repository import Gio
>>> Gio.File.new_for_uri("C:\\foo")
<__gi__.GDummyFile object at 0x00000000031b4a50 (GDummyFile at 0x0000000002def570)>
>>> a = Gio.File.new_for_uri("C:\\foo")
>>> a.get_uri()
'C:\\foo'
>>> a.get_uri_scheme()
'c'
```

**Comment by federicomenaquintero** [comment]
Moved to https://gitlab.gnome.org/GNOME/librsvg/issues/490 for reference.

**Comment by gbtami** [comment]
Can anyone update MINGW package if upstream fixed, please?

**Comment by kleisauke** [comment]
librsvg has been updated to 2.46.0 (PR https://github.com/msys2/MINGW-packages/pull/5797) which should fix this issue.

**Comment by Alexpux** [comment]
It not buildable for me

**Comment by kleisauke** [comment]
@Alexpux Could you try this patch?:
```diff
diff --git a/mingw-w64-librsvg/PKGBUILD b/mingw-w64-librsvg/PKGBUILD
index 1111111..2222222 100644
--- a/mingw-w64-librsvg/PKGBUILD
+++ b/mingw-w64-librsvg/PKGBUILD
@@ -14,7 +14,7 @@ makedepends=("${MINGW_PACKAGE_PREFIX}-gcc"
              "${MINGW_PACKAGE_PREFIX}-gdk-pixbuf2"
              "${MINGW_PACKAGE_PREFIX}-gobject-introspection"
              "${MINGW_PACKAGE_PREFIX}-vala"
-             "${MINGW_PACKAGE_PREFIX}-rust>=1.26"
+             "${MINGW_PACKAGE_PREFIX}-rust>=1.34"
              "setconf")
 depends=("${MINGW_PACKAGE_PREFIX}-gdk-pixbuf2"
          "${MINGW_PACKAGE_PREFIX}-pango"
@@ -50,12 +50,10 @@ build() {
     --host=${MINGW_CHOST} \
     --enable-introspection \
     --enable-vala \
-    --enable-silent-rules
+    --enable-silent-rules \
+    LIBS='-lws2_32 -luserenv' \
+    RUST_TARGET=$CARCH-pc-windows-gnu
 
-  # pass static rust package to linker
-  sed -i "s/^deplibs_check_method=.*/deplibs_check_method=\"pass_all\"/g" libtool
-  # add missing crt libs (ws2_32 and userenv) to LIBRSVG_LIBS
-  sed -i "s/^LIBRSVG_LIBS = .*/& -lws2_32 -luserenv/g" Makefile
   make
 }
 
````

**Comment by kleisauke** [comment]
fwiw, I'm able to build librsvg on Windows without this patch. Note that you have to open the MSYS2 command prompt as an administrator, otherwise the symlink would fail:
https://gitlab.gnome.org/GNOME/librsvg/blob/4df277869466fe28b6f95461657545c2b369d54a/librsvg/build.rs#L63
https://security.stackexchange.com/q/10194

**Comment by Alexpux** [comment]
Well we need to patch sources to not use symlink a, because using shell with administrator rights is not possible everytime

**Comment by kleisauke** [comment]
@Alexpux https://gitlab.gnome.org/GNOME/librsvg/merge_requests/242 should fix this.

**Comment by Alexpux** [comment]
@kleisauke  incorporated in https://github.com/msys2/MINGW-packages/commit/ea040f46148e75db9fa5acc8f44141e4a87ad56a
