### ISSUE TITLE
codelite package

### ISSUE THREAD

**Issue by davidwed** [msys2/MINGW-packages#5754]
In the codelite packages binarys are missing.

makedir.exe
wx-config.exe
codelite-clang-format.exe
codelite_launcher.exe

mingw32/mingw-w64-i686-codelite 13.0.0-1
mingw64/mingw-w64-x86_64-codelite 13.0.0-1

**Comment by revelator** [comment]
makedir.exe is just a replacement for the posix mkdir, and since we have a full msys2 shell it is not really needed. wx-config.exe is not part of codelite but wxwidgets, unfortunatly the wxwidgets package is built with autotools so wx-config is a script not an executable (not sure if it affects codelites ability to create gui's with wxwidgets or if it can pick up the script version if started from bash). 
codelite-clang-format.exe seems to be a plugin for clangs clang-format.exe, i suspect the reason it is not built is that it can use clangs clang-format.exe without the plugin when they are in the same dir.
codelite_launcher.exe is for using the IDE from say an usb stick and does not really apply to this package.
