### ISSUE TITLE
gcc trying to write a temporary file to C:\WINDOWS\ when no env

### ISSUE THREAD

**Issue by Hattshire** [msys2/MINGW-packages#5794]
This thing came up when trying to build MXE using msys2's mingw64, however something odd happens when trying to 'make' anything: for some reason instead of compiling or giving a compiler/pre-processor/etc error, it bails out with:

`Cannot create temporary file in C:\WINDOWS\: Permission denied`

------------
### Reproducing: 
Way 1:
clone _mxe/mxe.git@github_ and run `make nonet-lib`

**_Way 2:_**
Tracing down the making hole I came across this:
`/usr/bin/env --ignore-environment /mingw64/bin/gcc /home`
It should complain about "/home" being a dir, missing libraries(as msys's /usr/bin/gcc does) or something, but it errors on the tempfile thing 😢.

------------
Here is the environment I have from within the makefile (for Way 1)
```
LANG=en_US.UTF-8
MAKE_TERMOUT=/dev/pty1
MFLAGS=
SYSTEMROOT=C:\WINDOWS
PWD=/home/user/lightspark-0.8.1/build/mxe
HOME=/home/user
TERM=vt340
SHELL=/usr/bin/bash
WINDIR=C:\WINDOWS
MAKELEVEL=1
SHLVL=1
MAKE_TERMERR=/dev/pty1
ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
MSYSTEM=MINGW64
PATH=/home/user/lightspark-0.8.1/build/mxe/usr/x86_64-pc-mingw64/bin:/home/user/lightspark-0.8.1/build/mxe/usr/bin:/mingw64/bin:/mingw64/bin/site_perl/5.28.0:/mingw64/bin/vendor_perl:/mingw64/bin/core_perl:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/opt/xtensa-esp32-elf/bin
MAKEFLAGS=
_=/usr/bin/env

```

**Comment by revelator** [comment]
newer had any luck building MXE with MSYS2 you are probably better of building in win10 wsl environment since this package is geared more towards crosscompiling from linux to windows.

Not really sure why you need it though since Msys2 allready supports most of what MXE holds ?.

**Comment by MyNameIsTrez** [comment]
I was also getting `Cannot create temporary file in C:\WINDOWS\: Permission denied` whenever `C:/msys64/mingw64/bin/gcc.exe` was being run by a Makefile, where I manually ran the Makefile with `C:/msys64/usr/bin/make.exe` inside of a terminal.

Whenever I manually ran `C:/msys64/mingw64/bin/gcc.exe` inside of a terminal it ran just fine however!

I just had to go into VS Code's properties to always run it as an administrator, see [here](https://stackoverflow.com/a/39948482/13279557).

**Comment by thautwarm** [comment]
Rebooting my machine works for this issue..

**Comment by fksune** [comment]
had the same issue when I run `make` from Git Bash (worked fine on other shells and the MSYS environments tho). TMP and TEMP are missing when printing the `env` vars from the Makefile, so I guess `make` tried accessing TEMP directory on windows root (`C:\WINDOWS\`) and consequently got a permission error. not sure how it ended up like this as both TMP and TEMP are defined in Git Bash. This is most likely because `make` spawns shells on its own for running the recipes, and they don't have all the env vars properly configured (try printing $SHELL from the Makefile, in my case it shows `/usr/bin/sh`).

I ended up using the environment variables override flag in make. `make -e TMP=<PATH_TO_TEMP>` which worked for me!
