### ISSUE TITLE
Vulkan/GLFW3:  Vulkan instance missing VK_KHR_win32_surface extension

### ISSUE THREAD

**Issue by andreasdr** [msys2/MINGW-packages#5812]
Hi,

my Vulkan initialization used to work a few weeks ago with MSYS2/X64. But now I get "Vulkan instance missing VK_KHR_win32_surface extension" when executing the following statement.
- glfwCreateWindowSurface(inst, Application::glfwWindow, NULL, &surface)

Seems like there were some recent changes in vulkan or glfw3 that causes this error now.
Or somethin in msys2? No idea.

Please check.

Many thanx and best regards
Andreas

**Comment by StarWolf3000** [comment]
Make sure your graphics drivers are up-to-date.

**Comment by andreasdr** [comment]
They are!

**Comment by andreasdr** [comment]
Hi, 

I close this issue.

I needed to link against vulkan-1.dll from VulkanSDK runtime. Then everything just works.

Sorry for the noise.

**Comment by DavidEGrayson** [comment]
I'm running into the same issue.  MSYS2 provides a Vulkan implementation in the `mingw-w64-x86_64-vulkan-loader` and `mingw-w64-x86_64-vulkan-headers` packages, so I think the preferred solution would be to use that loader instead of using some external library.  Perhaps we need to patch GLFW to look for a Vulkan implementation inside MSYS2 before going to external locations?  It would be bad if we try to ship a Vulkan application in MSYS2, and its behavior depends on whether a Vulkan SDK is installed.

To test this problem, I wrote a simple C program that just:

1. Starts with these headers
      #define VK_USE_PLATFORM_WIN32_KHR
      #include <vulkan/vulkan.h>
      #define GLFW_EXPOSE_NATIVE_WIN32
      #include <GLFW/glfw3.h>
      #include <GLFW/glfw3native.h>
2. Creates a window with `glfwCreateWindow`.
3. Creates a Vulkan instance with `vkCreateInstance`, possibly requesting the `VK_LAYER_KHRONOS_validation` layer (I choose at compile time).
4. Creates a Vulkan surface with either `vkCreateWin32SurfaceKHR` or `glfwCreateWindowSurface` (I choose at compile time).

Here are my results:

|C:/VulkanSDK|Request layer VK_LAYER_KHRONOS_validation|Surface creation func|Result|
|--|--|--|--|
|Removed|Yes|N/A|Instance creation fails with VK_ERROR_LAYER_NOT_PRESENT|
|Removed|No|vkCreateWin32SurfaceKHR|Works|
|Removed|No|glfwCreateWindowSurface|Surface creation failed: "Vulkan instance missing VK_KHR_win32_surface extension"|
|Present|either|vkCreateWin32SurfaceKHR|Works|
|Present|either|glfwCreateWindowSurface|Surface creation failed: "Vulkan instance missing VK_KHR_win32_surface extension"|
