### ISSUE TITLE
[libutf8proc] Invalid checksums

### ISSUE THREAD

**Issue by extratype** [msys2/MINGW-packages#5927]
The PGP signature is correct but the checksums are different.

[Info](https://packages.msys2.org/package/mingw-w64-x86_64-libutf8proc?repo=mingw64)

* MD5: ``0e2c6d52dbf599d97d6d49ce76d44c6d``
* SHA256: ``ffba8ab9548b860ff64402dea6ec05f65906e31fc2a963acfa2b9a43f4a84e60``

[File](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libutf8proc-2.4.0-1-any.pkg.tar.xz)

* MD5: ``5f6f9aa6ee50629aa8247b321fa1c4f6``
* SHA256: ``31062643300ce29a509fef8f80320cba7fb887354d064f037a4f6256783b1292``

Found the same problem in https://github.com/msys2/MSYS2-packages/issues/1693#issuecomment-549129135.

**Comment by lazka** [comment]
Likely because it uses the github source tarballs, which are re-generated from time to time and not stable.

upstream would need to provide their own source tarballs.

**Comment by revelator** [comment]
which is why i mostly do updpkgsums followed by build command on packages that are as yet unstable.
best practice i found so far building was doing it in as short a path as possible (preferably root) so something like this -> rm -rf /G/mingw-w64-* && updpkgsums && BUILDDIR=/G makepkg-mingw -c -i + other flags as needed. This allmost allways works even on problematic packages (eg. some packages dont like long paths or paths with spaces in them).

**Comment by lazka** [comment]
yeah. not much we can do here, feel free to ask upstream for a stable release tarball.
