### ISSUE TITLE
cmake never creates import libraries for executables

### ISSUE THREAD

**Issue by Kha** [msys2/MINGW-packages#5952]
Upstream cmake always creates implibs for executables, [mingw-w64-cmake never does](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cmake/0007-Do-not-generate-import-libs-for-exes.patch). According to the [docs](https://cmake.org/cmake/help/latest/prop_tgt/ENABLE_EXPORTS.html#prop_tgt:ENABLE_EXPORTS), it should actually depend on `ENABLE_EXPORTS`. While this use case is rare, I believe it is the correct way to build plugin libraries that use symbols of an executable they are loaded into.

Currently I'm using
```
target_link_options(foo PRIVATE "-Wl,--out-implib,$<TARGET_LINKER_FILE:foo>")
```
as a workaround.

**Comment by oscarfv** [comment]
Usually executables are not used as shared libraries, which IIUC is what you need. Creating an import library for every `.exe` is wasteful.

On my pluging-based apps, the application is compiled into a dll. Plugins link to that dll. There is a tiny exe that loads and runs the dll.

**Comment by Kha** [comment]
> Creating an import library for every .exe is wasteful.

Yes, which is supposedly why `ENABLE_EXPORTS` exists (except for the fact that it is ignored in this regard by both upstream and the mingw patch, of course). The cmake docs literally describe the use case of "loadable modules", i.e. plugins.

**Comment by Kha** [comment]
For a cross-platform discussion see also https://github.com/leanprover/lean4/pull/59#issuecomment-552124208.

**Comment by oscarfv** [comment]
If ENABLE_EXPORTS does not create an export library, that's a bug, because [the documentation says](https://cmake.org/cmake/help/latest/prop_tgt/ENABLE_EXPORTS.html):

```
On Windows-based systems (including Cygwin) an “import library” is created along with the executable to list the exported symbols. Loadable modules link to the import library to get the symbols.
```

I just tried ENABLE_EXPORTS on one of my projects and the export library is not created. This is a bug that should be reported upstream.

**Comment by oscarfv** [comment]
@Kha : if you create a bug report upstream please reference it here. Thanks.

**Comment by mati865** [comment]
@oscarfv the issue could be caused by this patch: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cmake/0007-Do-not-generate-import-libs-for-exes.patch (it was linked in the first post).

**Comment by Kha** [comment]
Yes, it is only mingw cmake that breaks my build! Upstream's behavior should perhaps be changed as well, but at least it is not broken, just wasteful.

**Comment by oscarfv** [comment]
@mati865 : without that patch cmake always generates an import library for an executable. Upstream could argue that ENABLE_EXPORTS "works" in that sense, but that's a very poor implementation. The import library should be created only when requested.

Of course our patch is very relevant because the upstream bug report should not be about ENABLE_EXPORTS not creating the import library, but about the import library being created even when ENABLE_EXPORTS if OFF.

**Comment by oscarfv** [comment]
@Kha : doing something to support a somewhat exotic use case at the expense of being wasteful for the vast majority of projects is not acceptable, IMHO, much less so when there is an easy workaround.

**Comment by Kha** [comment]
Fixed in https://github.com/msys2/MINGW-packages/commit/76446f4dfeffbfc47ffb5b428c2a7b288b49a44b#diff-83c660446390e434bf119a70b53fa44b4075090ea1cb9e5e7c0c05e74c28473a
