### ISSUE TITLE
How can we have sys/mman.h on Mingw64

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MINGW-packages#6002]
How can we have code
`#include sys/mman.h `
satisfied, as the demanding build gave:
```
  fatal error: sys/mman.h: No such file or directory
   40 | #include <sys/mman.h>

```
Please try to do it. Thanks.

**Comment by lazka** [comment]
That's not a Windows header.

**Comment by revelator** [comment]
there was a project some years back that attempted to emulate mman behaviour mman-win32 i think it was named. But i would not recommend using it unless for porting stuff since it would break numerous other packages if left installed. The library from this project itself is static so once used you can remove it and the header again without breaking things.

**Comment by abdulbadii** [comment]
I see..
