### ISSUE TITLE
Static linking of libgcc and stdc++ is broken

### ISSUE THREAD

**Issue by ienapliss** [msys2/MINGW-packages#6163]
Static linking standard libs with "-static -static-libgcc -static-libstdc++" still requires the program to use "libstdc++-6.dll" in 32bit-mode and "libgcc_s_seh-1.dll" in 64bit mode!

Now, I don't want to know why there is this strange behavior with 32vs64 requiring one or the other, but is it possible to actually ship single binary nowdays on windows with gcc?

**Comment by lazka** [comment]
Searching for this suggests using "-static-libstdc++ -static-libgcc", but that's all I know about this..

**Comment by revelator** [comment]
not easily no, the problem with libstdc++ is that the compiler uses some code to determine if a static link would cause problems and no matter the flag it will then allways link to the dll version of libstdc++.
I ported TDM's patchset to gcc-9.2.0 which allows bypassing this behaviour as it will allways link statically to gcc's runtime libraries unless specified that you want to link to the dll versions (so in fact the reverse of the normal behaviour), still it will at times link to libstdc++ dll unless you rename libstdc++.dll.a to libstdc++_s.dll.a. 

The code for this behaviour is located in gcc-9.2.0.a/gcc/cp/g++spec.c if you want a look at how it is done.

**Comment by Optiligence** [comment]
`-static` works fine, gotta make sure your direct and transitive dependencies are also static though.

**Comment by revelator** [comment]
Aye if all dependencies are static then it should work.

**Comment by thefallentree** [comment]
works for me.

**Comment by revelator** [comment]
just an addition to this.
-static-libstdc++ does not work if it is a C program/library linking to libstdc++ because the -static-libstdc++ flag is only understood by g++ while gcc will treat -lstdc++ as a shared library despite setting the -static-libstdc++ flag.
to get around such cases one would have to modify the build chain using -B,-static -lstdc++ -B,-dynamic or use an even uglier way to point it to the static libstdc++.a file. furthermore since there seems to be some confusion about these flags (no they dont mean your program gets statically linked !!!. they mean the program/library links to the compilers static runtime libraries eg. libgcc.a/libstdc++.a). everything else is still built shared unless you use -static.
