### ISSUE TITLE
"import imobiledevice" fails

### ISSUE THREAD

**Issue by MobilEKG** [msys2/MINGW-packages#6709]
After update msys2 by using
```
pacman -Sydd pacman
pacman -Syuu 
```

Python code `import imobiledevice` fails: 
_**ImportError: DLL load failed while importing imobiledevice: The specified module could not be found.**_

Is there anything missing?

Related package:
https://packages.msys2.org/package/mingw-w64-x86_64-libimobiledevice

**Comment by MobilEKG** [comment]
Move to https://github.com/msys2/MSYS2-packages/issues/2061#issue-665665615

**Comment by Biswa96** [comment]
This issue is related to mingw packages so this is the right place. The issue is related to import library of `libimobiledevice.dll`. `libimobiledevice.dll` is linked with `libplist.dll` but the actual file name is `libplist-2.0.dll`. See this following output:

```
$ ntldd /mingw64/bin/libimobiledevice.dll
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000000000cc0000)
        msvcrt.dll => C:\Windows\SYSTEM32\msvcrt.dll (0x00000000013e0000)
        ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x0000000000cc0000)
        SHELL32.dll => C:\Windows\SYSTEM32\SHELL32.dll (0x00000000013d0000)
        WS2_32.dll => C:\Windows\SYSTEM32\WS2_32.dll (0x0000000000ea0000)
        libcrypto-1_1-x64.dll => F:\msys64\mingw64\bin\libcrypto-1_1-x64.dll (0x0000000000cc0000)
        libplist.dll => not found
        libssl-1_1-x64.dll => F:\msys64\mingw64\bin\libssl-1_1-x64.dll (0x0000000000cc0000)
        libusbmuxd.dll => F:\msys64\mingw64\bin\libusbmuxd.dll (0x0000000000b40000)
```

I can not rebuild the package because the autoconf can't find the dependencies (libusbmuxd and libplist). I am not sure how it was built as first place.
