### ISSUE TITLE
Blender is missing a dependency

### ISSUE THREAD

**Issue by ghost** [msys2/MINGW-packages#6737]
The `mingw-w64-x86_64-blender` package seems to depend on `mingw-w64-x86_64-openvdb`, but this isn't listed as a dependency and installed automatically. After I installed blender I got a DLL not found error for `libopenvdb.dll`, and installing `mingw-w64-x86_64-openvdb` fixed it.

**Comment by lazka** [comment]
PR welcome

**Comment by BessieTheCow** [comment]
I noticed that the line is commented out with the text `# there are missing export symbols in openvdb DLL`. I'm not familiar with this stuff and I have no idea what that means.

**Comment by revelator** [comment]
Means some nessesary function names are not exported correctly to the library so a blender build might keel over because it cannot find them.  One way to get around missing exports would be to add -Wl,--export all-symbols to the linker flags, there was another package which had this problem namely mlpack which was caused by lack of that specific functionality in cmake (worked in msvc not so much with gcc).

**Comment by MehdiChinoune** [comment]
fixed, blender now builds with OpenVDB.
