### ISSUE TITLE
mingw-w64-i686-pkg-config-0.29.2-1 cannot be downloaded

### ISSUE THREAD

**Issue by chuah1** [msys2/MINGW-packages#6835]
On the site https://packages.msys2.org/package/mingw-w64-i686-pkg-config?repo=mingw32
The file https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz could not be downloaded.  Any idea where I can get it?

**Comment by chuah1** [comment]
I used Edge browser, I just tried Google Chrome with no luck.  Then I tried using a different computer and I was able to download that.  Must be something weird with the network.  I appreciate your getting back to me so quickly.

**Comment by lazka** [comment]
We also have various mirrors if you hit this problem again: https://github.com/msys2/MSYS2-packages/blob/master/pacman-mirrors/mirrorlist.mingw32

**Comment by Tobita0815** [comment]
Same problem here. I have tried the latest versions of Edge, Chrome and Firefox. Everywhere I get a timeout. The problem is that I cannot download the package with vcpkg.

**Comment by quatmax** [comment]
vcpkg build is currently down:
if you look at: https://www.msys2.org/ 

`The primary download server is currently (since Oct 2nd) down. We are working on bringing it back up. Pacman has preconfigured mirrors so package installations should work, albeit with timeouts. The setup package can be downloaded from SourceForge or GitHub.`

**Comment by quatmax** [comment]
https://github.com/microsoft/vcpkg/issues/13871
