### ISSUE TITLE
[Discussion] Allowing mingw32/64 only packages

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#7041]
With the current system adding the following to the PKGBUILD

```bash
[[ $MINGW_PACKAGE_PREFIX = "mingw-w64-i686" ]] && exit 0;
```

would result in `makepkg-mingw --printsrcinfo` skipping that arch and msys2-autobuild not building it.

* Should we allow such packages?
* Is the above too hacky? Other ideas?

Somewhat related, I was also thinking of adding a new wrapper, `makepkg-msys2 mingw32 <args>` as a replacement for supporting more subsystems like clang or ucrt.

**Comment by mati865** [comment]
Somewhat related: for clang subsystem I'd love to support only 64 bit packages.
Main reason is LLD which due to it's design needs big address space: https://github.com/mstorsjo/llvm-mingw/issues/151. Probably creating Large Address Aware binaries could help *in some cases* but I haven't investigated. Another possibility is using multilib approach instead of multiarch that is currently used.
Another reason is 32-bit systems are not really common these days, in Linux world may distros already dropped 32-bit images. Main subsystem supports 32-bit executables and dropping it would be "breaking change", it'd be great to avoid this legacy with new subsystems.

> Somewhat related, I was also thinking of adding a new wrapper, makepkg-msys2 mingw32 <args> as a replacement for supporting more subsystems like clang or ucrt.

There is `makepkg-clang` installed by default that uses `/clang{32,64}` directories.

**Comment by Biswa96** [comment]
How about adding an option in makepkg-mingw shell script to choose:

1. Target architectures: Possible values  = {x86, x86_64, aarch64, armv7}
and/or
2. Build environments: Possible values = {msvcrt, ucrt, binutils/gcc, llvm/clang}

**Comment by lazka** [comment]
> Somewhat related: for clang subsystem I'd love to support only 64 bit packages.

Sounds good

> There is `makepkg-clang` installed by default that uses `/clang{32,64}` directories.

I wanted to avoid having 5 tolls for the same thing. But yeah, not sure..

> How about adding an option in makepkg-mingw shell script to choose:

Sounds good (if someone can make the arg parsing/forwarding work)

**Comment by mati865** [comment]
> How about adding an option in makepkg-mingw shell script to choose:

This may get a bit hard since you cannot use GNU tools for ARMv7 and AArch64, neither GCC not Binutils support them as MinGW target.
Right now the only way to go for ARM is replacing GCC with Clang, libgcc with compiler-rt, libgcc exceptions with libunwind, libstdc++ with libc++, GNU AS with LLVM, and BFD with LLD. This might change in the future however.

**Comment by Biswa96** [comment]
I know that. I mentioned those as possible values. In my msys2 system, I have a mingwarm64 folder dedicated to llvm-mingw and 10-15 low dependent aarch64 packages.

**Comment by Biswa96** [comment]
I mentioned those just as possible values.

**Comment by oscarfv** [comment]
Having mingw64 only for those packages which are problematic on mingw32 sounds good, but I hope this is not the first step towards a not-so-distant removal of mingw32. There are still many 32 bits machines around, plus the 64 bits architecture sometimes considerably increases RAM requirements for no gain.

**Comment by umarcor** [comment]
Is there a discussion about why `arch=('any')` is the current default instead of `arch=(i686, x86_64)`?

**Comment by lazka** [comment]
> Is there a discussion about why `arch=('any')` is the current default instead of `arch=(i686, x86_64)`?

So you can install mingw32 and mingw64 packages at the same time with pacman.

**Comment by mati865** [comment]
@umarcor `arch` relates to MSYS2 architecture, package with `arch=(x86_64)` would be installable only on 64-bit MSYS2 but the package would be still built for `mingw32` and `mingw64` subsystems.

**Comment by MehdiChinoune** [comment]
Fixed by #10910
