### ISSUE TITLE
lis - Still "Incoming New Packages"

### ISSUE THREAD

**Issue by 3rav** [msys2/MINGW-packages#7482]
What could be the reason why the package "mingw-w64-lis" is still unavailable (from 2020-11-29 still "Incoming New Packages")?

**Comment by ImperatorS79** [comment]
Same question for the update of opencascade to 7.5.0 ^^.

**Comment by umarcor** [comment]
After the PRs are merged, the [msys2/msys2-autobuild](https://github.com/msys2/msys2-autobuild) repository needs to build the packages. That is done every 4-6h. The artifacts/assets are uploaded to https://github.com/msys2/msys2-autobuild/releases. Then, some maintainer needs to manually sign them and upload them to the repositories. While packages are in autobuild releases but not signed/uploaded yet, you can find them shown in https://packages.msys2.org/new or https://packages.msys2.org/queue.

@3rav, 'lis' is shown in https://github.com/msys2/msys2-autobuild/releases/tag/staging-mingw.

@ImperatorS79, 'opencascade' was skipped by the autobuilder because it depends on 'openblas': https://github.com/msys2/msys2-autobuild/runs/1602221517?check_suite_focus=true#step:8:100.

**Comment by ImperatorS79** [comment]
And why does it skip it ? What happens with openblas ? What can I do ?

**Comment by umarcor** [comment]
The reason is shown by the autobuilder. It was skipped because it depended on openblas being updated first. It seems that openblas was built during these last 2-3 days, and it's now shown in https://github.com/msys2/msys2-autobuild/releases/tag/staging-mingw. Hence, opencascade is not blocked by that anymore. Now, the reason is "*requires: mingw-w64-cmake*". See https://github.com/msys2/msys2-autobuild/runs/1611128487?check_suite_focus=true#step:8:140. Moreover, cmake is currently being skipped because of "*requires: mingw-w64-qt5*": https://github.com/msys2/msys2-autobuild/runs/1611128487?check_suite_focus=true#step:8:89. And qt5 is failing: https://github.com/msys2/msys2-autobuild/runs/1611128487?check_suite_focus=true#step:8:80.

There is little you/we can do, other than waiting or trying to help with fixing whichever issue that is making qt5 fail.

**Comment by lazka** [comment]
it's in the repo now.

**Comment by 3rav** [comment]
Great
