### ISSUE TITLE
Is there a single petsc lib file?

### ISSUE THREAD

**Issue by ceanwang** [msys2/MINGW-packages#7871]
I installed petsc following here https://packages.msys2.org/package/mingw-w64-x86_64-petsc?repo=mingw64

At the bottom of that page, it lists all files installed. But I can't find a single libpetsc.a file which my program can link to. Instead it has many libs like libpetscsnes.a, libpetscvec.a, and so on.

It seems this build is ./configured PETSc with the option --with-single-library=0 

Could we have a build --with-single-library=1, so only one single libpetsc.a will be generated. That would be more easy to link to.

The same problem with slepc package and  mumps package.

Regards,

Cean

**Comment by lazka** [comment]
@okhlybov any thoughts on this?

**Comment by okhlybov** [comment]
A compilation with --with-single-library=1 won't work on Windows due to inherent command line length limitation.

In fact, there **is** a single libpetsc-${xyz}.a static library organized as a thin archive which it a kind of import library for all constituent archives in roughly the same way as  libpetsc-${xyz}.dll.a does for the respective DLL.

Moreover, the `petsc` package provides multiple PETSc library builds for all scalar types and threading models differentiated by the **xyz** suffix, where **x**  denotes scalar type in the Netlib's standard **sdcz** notation, **y** denotes the threading model with **s** for sequential, **t** for multithreaded and **m** for MPI build and finally **z** denotes optimization level with **o** for optimized build.

In order to keep the global include and lib directories clear of these multpile repeating files, they are kept in the build-specific `include/petsc/${xyz}` and `lib/petsc/${xyz}` subdirectories .

Hence I's suggest @ceanwang to use PkgConfig to obtain command line flags as it hides all these complexities altogether.

For example, the command
```shell
pkgconf petsc-dmo --libs
```
outputs linking flags for the double precision MPI build.

Conversely, the command
```shell
pkgconf petsc-dmo --cflags
```
is to obtain the respective compilation flags.

The same scheme applies to SLEPc.

**Comment by ceanwang** [comment]
There was a long talk here. Where is petscfix.h? (#820) · Issues · PETSc / petsc · GitLab Sent from Mail for Windows 10 From: Oleg A. KhlybovA compilation with --with-single-library=1 won't work on Windows due to inherent command line length limitation.

**Comment by okhlybov** [comment]
> Where is petscfix.h?

include/petsc/${xyz}/petscfix.h

**Comment by MehdiChinoune** [comment]
Fixed by #9166
