### ISSUE TITLE
ming64_64 host type set to mingw32

### ISSUE THREAD

**Issue by rmottola** [msys2/MINGW-packages#8020]
when using "mingw64" shell, the host type is set to:
`MSYSTEM_CHOST=x86_64-w64-mingw32`

on "mingw32" it is set to
`MSYSTEM_CHOST=i686-w64-mingw32`

I think this is counter-intuitive, it forces me to configure certain software on ming64 with `--host=mingw64`

Wouldn't it be better to set it right?

The setting comes from `/mingw64/etc/config.site`:
`# Set default 'host' to speedup configure
if test -z "$build_alias"; then
  build_alias="${MSYSTEM_CHOST-x86_64-w64-mingw32}" && \
    ${as_echo-echo} "$config_site_me:${as_lineno-$LINENO}: default build_alias set to $build_alias" >&5
fi
`

**Comment by 1480c1** [comment]
I'm not sure how this is counter-intuitive as x86 32-bit == i686 for a lot of systems and x86_64 64-bit == x86_64, and the `MSYSTEM_CHOST` is usually used to get the "cross-prefix" for binaries (on ubuntu, it's `i686-w64-mingw32-gcc` and `x86_64-w64-mingw32-gcc`

**Comment by rmottola** [comment]
sorry for being not clear, x86_64 is fine! but if I am in mingw64, I need 64 bit so
MSYSTEM_CHOST=x86_64-w64-mingw32 shoud be MSYSTEM_CHOST=x86_64-w64-mingw64 perhaps? I need the "host" part to be ming64 to have certain software to configure correctly.

**Comment by 1480c1** [comment]
I'm not sure where it would be best to take it up with (maybe gcc?) as the `x86_64-w64-mingw32` form is widely used and I don't know if it would be easy or even possible to change it now

**Comment by Biswa96** [comment]
Yeah, that's somewhat confusing at first. The `mingw32` comes from target triplet. If you are interested in details see this thread https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/CABrM6wmrTnm9jFjZzzmbDk1XzrNUT34GT7zJ4w_n5T6fF9abEQ%40mail.gmail.com/#msg37194346.

**Comment by rmottola** [comment]
Yes... confusing, but not a "bug", sorry - I close it.

 I think the good explanation is here:



This triplet specifies where the executables produced by this program (gcc) will run. Originally the 
MinGW.org project chose `*-pc-mingw32`, so we selected `*-w64-mingw32` to avoid the conflict.

There is no special meaning about `w64` itself. `mingw32` on the other hand specifies the ABI, so 
all `i686-*-mingw32` targets are considered ABI-compatible.

Neither does `w64` specify the target is 64-bit, nor does `mingw32` specify the target is 32-bit. 
They are just hard-coded names.

**Comment by FrankHB** [comment]
The [official wiki of MinGW-w64](https://sourceforge.net/p/mingw-w64/wiki2/TypeTriplets/) refers to `config.guess` and `config.sub`. However, the source of [config.guess](https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD) and [config.sub](https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD) do guess the triplet for 64-bit MinGW as $UNAME_MACHINE-pc-mingw**64** instead of `$UNAME_MACHINE-pc-mingw32`.

That document is unclear about [how w64 come from](https://www.gnu.org/prep/standards/html_node/System-Portability.html#System-Portability). That is, it actually does have some special meaning before MinGW-w64 choose the name.

Anyway, the inconsistency suggests it a bug, at least for one of MinGW-w64 and GNU guess. @rmottola what do you think about? Is it appropriate to forward to upstream?
