### ISSUE TITLE
[Suggestion] Deprecate mingw32

### ISSUE THREAD

**Issue by TheMadHau5** [msys2/MINGW-packages#8218]
As it seems that new subsystems (ucrt, clang and soon arm) are being added, all 64-bit, it seems logical to deprecate the mingw32 subsystem in favour of mingw64, as the former is barely used any longer. Once this is final, it can then be removed. This should also relieve some load off the package maintainers.

**Comment by Biswa96** [comment]
The time has not arrived yet 😌

**Comment by 1480c1** [comment]
Maybe better to switch to discussion format (ping @lazka)

I'm hesitant to say that we should on the account that even though it definitely would reduce maintenance burden on a lot of people, it may cause a lot of issues as there are still some people who use the 32-bit toolchain and packages because their downstream users still might use 32-bit binaries
