### ISSUE TITLE
CMake pkgconfig patch upstream

### ISSUE THREAD

**Issue by orgads** [msys2/MINGW-packages#8255]
Hi,

CMake package has a patch that introduces a global define for passing `--dont-define-prefix` to pkgconfig. I tried to upstream this patch, but couldn't explain the reasoning. The flag is used in [libgit2](https://github.com/msys2/MINGW-packages/commit/9215e839df3c4f98ea4b160831c17ddada121dfa) and in [opencv](https://github.com/msys2/MINGW-packages/commit/772198abbc48b33be4d324330a6e08c8b1476a11) packages.

@Alexpux Can you please explain why this flag is needed? You can reply here or on my merge request there: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5930, or even better - file an issue for cmake.

Thanks.

**Comment by lazka** [comment]
Thanks, we should look if they are really needed.

**Comment by 1480c1** [comment]
from what I can see in the output, having that flag in the line will make sure it prints out the `-L` and `-I` flags even if it's within one of the "system" locations, but I think the flag is supposed to work with issues where includepath and libpath are set to full paths instead of being generated based on prefix and the package is relocated

**Comment by 1480c1** [comment]
https://stackoverflow.com/questions/52440511/why-pkg-config-overrides-prefix-with-another-default-one

seems to answer more on what it does, looking at https://github.com/pkgconf/pkgconf/pull/211, it seems we might be able to drop that patch and instead set `PKG_CONFIG_DONT_DEFINE_PREFIX` env variable instead since we now use pkgconf as the default

**Comment by lazka** [comment]
libgit builds fine without this, so I think I'll just remove it
