### ISSUE TITLE
[boost]: build error with UCRT re mbstate_t

### ISSUE THREAD

**Issue by lazka** [msys2/MINGW-packages#8283]
It's hitting a non-ucrt branch in mingw-w64 somehow, which leads to a wrongly defined `mbstate_t`:

```c
In file included from C:/msys64/ucrt64/include/c++/10.2.0/cwchar:44,
                 from C:/msys64/ucrt64/include/c++/10.2.0/bits/postypes.h:40,
                 from C:/msys64/ucrt64/include/c++/10.2.0/iosfwd:40,
                 from C:/msys64/ucrt64/include/c++/10.2.0/ios:38,
                 from libs\log\src\setup\init_from_settings.cpp:28:
C:/msys64/ucrt64/x86_64-w64-mingw32/include/wchar.h:1445:2: error: #error "foo"
 1445 | #error "foo"
      |  ^~~~~
```

```c
#if defined(_UCRT) || defined(__LARGE_MBSTATE_T)
  typedef struct _Mbstatet {
    unsigned long _Wchar;
    unsigned short _Byte, _State;
  } _Mbstatet;
  typedef _Mbstatet mbstate_t;
#else
#error "foo"
  typedef int mbstate_t;
#endif
```

Posting here so I can link to it in the PKGBUILD

boost build error:

```

C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.text+0x156): undefined reference to `std::codecvt<wchar_t, char, int> const& std::use_facet<std::codecvt<wchar_t, char, int> >(std::locale const&)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.text+0x1b2): undefined reference to `std::codecvt<wchar_t, char, int> const& std::use_facet<std::codecvt<wchar_t, char, int> >(std::locale const&)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.text+0x324): undefined reference to `std::codecvt<wchar_t, char, int> const& std::use_facet<std::codecvt<wchar_t, char, int> >(std::locale const&)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.text+0x4e4): undefined reference to `std::codecvt<wchar_t, char, int> const& std::use_facet<std::codecvt<wchar_t, char, int> >(std::locale const&)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.rdata$.refptr._ZNSt7codecvtIDiciE2idE[.refptr._ZNSt7codecvtIDiciE2idE]+0x0): undefined reference to `std::codecvt<char32_t, char, int>::id'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/code_conversion.o:code_conversion.cpp:(.rdata$.refptr._ZNSt7codecvtIDsciE2idE[.refptr._ZNSt7codecvtIDsciE2idE]+0x0): undefined reference to `std::codecvt<char16_t, char, int>::id'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/record_ostream.o:record_ostream.cpp:(.text$_ZNK5boost3log9v2_mt_nt63aux22basic_ostringstreambufIcSt11char_traitsIcESaIcEE21length_until_boundaryEPKcyyNS_17integral_constantIbLb1EEE[_ZNK5boost3log9v2_mt_nt63aux22basic_ostringstreambufIcSt11char_traitsIcESaIcEE21length_until_boundaryEPKcyyNS_17integral_constantIbLb1EEE]+0x36): undefined reference to `std::codecvt<wchar_t, char, int> const& std::use_facet<std::codecvt<wchar_t, char, int> >(std::locale const&)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/record_ostream.o:record_ostream.cpp:(.rdata$_ZTVN5boost3log9v2_mt_nt63aux22basic_ostringstreambufIwSt11char_traitsIwESaIwEEE[_ZTVN5boost3log9v2_mt_nt63aux22basic_ostringstreambufIwSt11char_traitsIwESaIwEEE]+0x38): undefined reference to `std::basic_streambuf<wchar_t, std::char_traits<wchar_t> >::seekpos(std::fpos<int>, std::_Ios_Openmode)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/record_ostream.o:record_ostream.cpp:(.rdata$_ZTVN5boost3log9v2_mt_nt63aux22basic_ostringstreambufIcSt11char_traitsIcESaIcEEE[_ZTVN5boost3log9v2_mt_nt63aux22basic_ostringstreambufIcSt11char_traitsIcESaIcEEE]+0x38): undefined reference to `std::basic_streambuf<char, std::char_traits<char> >::seekpos(std::fpos<int>, std::_Ios_Openmode)'
C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: bin.v2/libs/log/build/gcc-10.2.0/release/pch-off/threadapi-win32/threading-multi/visibility-hidden/process_name.o:process_name.cpp:(.text$_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x38): undefined reference to `__imp__ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt7codecvtIwciE'
```

**Comment by Biswa96** [comment]
@mstorsjo was waiting for this type of issue...

**Comment by lazka** [comment]
Boost forces __MSVCRT_VERSION__  in various places: https://github.com/boostorg/nowide/blob/8d86904d88d77f33d07077933f9c19da64583c8b/include/boost/nowide/config.hpp#L20

**Comment by lazka** [comment]
Patched and upstreamed:

* https://github.com/boostorg/nowide/pull/130
* https://github.com/boostorg/log/pull/149

**Comment by lazka** [comment]
@lhmouse somewhat related, should this be setting `__MSVCRT_VERSION__`: https://github.com/mirror/mingw-w64/blob/2afb89e6a651f9c5749d9de492a263e03ba1e94e/mingw-w64-crt/Makefile.am#L23 ?

**Comment by lhmouse** [comment]
See https://github.com/mirror/mingw-w64/commit/ad131bcb16baf29daed376c260b0a62e7fa59ab0.

**Comment by lazka** [comment]
ok, Iooked through the git history and pre the above commit there was no way to set a default `__MSVCRT_VERSION__`, which might explain why boost did it.

> See [mirror/mingw-w64@ad131bc](https://github.com/mirror/mingw-w64/commit/ad131bcb16baf29daed376c260b0a62e7fa59ab0).

that commit doesn't explain why though.. but ok :)

**Comment by mstorsjo** [comment]
> ok, Iooked through the git history and pre the above commit there was no way to set a default `__MSVCRT_VERSION__`, which might explain why boost did it.
> 
> > See [mirror/mingw-w64@ad131bc](https://github.com/mirror/mingw-w64/commit/ad131bcb16baf29daed376c260b0a62e7fa59ab0).
> 
> that commit doesn't explain why though.. but ok :)

So, regardless of what crt you choose as default, it builds the import libraries of all crt variants, libucrtbase.a, libmsvcr70.a etc, and libmsvcrt-os.a. The latter is the import library for linking against the msvcrt.dll that ships with the os. Libmsvcrt.a, which is the one that is linked implicitly as default, is a copy of the one you chose to be default.

The intent is that you can link against a non-default CRT too, you just need to make sure to only link against the right `lib*crt*.a` and not against `libmsvcrt.a`. With gcc, you need to use a custom spec file to make it stop adding `-lmsvcrt`. With clang (which doesn't support spec files), it drops the implicit `-lmsvcrt` if you add a custom `-lmsvcr*` or `-lucrt*` option.

In addition to linking the right lib, you obviously need to build all object files with the right `-D_UCRT` or `-D__MSVCRT_VERSION__=` if you want to use a non-default crt.

While linking this way, you still link in object files from `libmingw32.a` and `libmingwex.a` (and `crt*.o`). The intent is that these should be crt independent, so that anything you use there should work with any choice of crt.

So therefore, libmingwex.a, libmingw32.a, `crt*.o` all get built with the same default `-D__MSVCRT_VERSION__=` setting, making them consistent. If there's something that can't be done in a compatible way, those object files need to move to `lib*crt*.a` instead, so there's a version that matches the choice of crt.

Some source files that need it, e.g. the ones that go into `libucrt*.a`, override the crt choice in their C sources, before including headers.

I guess I should send a patch for mingw-w64 to clarify that line.

> imo mingw-w64 should just re-define `__MSVCRT_VERSION__` and `_UCRT` if users shouldn't be allowed to change it.

Well you are supposed to be able to change it for anything on top of the mingw-w64-crt - but if you're linking e.g. libstdc++ that is built for one specific crt, you can't choose differently. Iirc libgcc might also lock you to the initial choice (while it works fine to choose a different crt when using compiler-rt builtins).
