### ISSUE TITLE
Help wanted with exception handling models in MinGW

### ISSUE THREAD

**Issue by triplef** [msys2/MINGW-packages#8287]
We’ve been [working](https://github.com/gnustep/libobjc2/pull/190) on adding support for MinGW to the GNUstep Objective-C Runtime (aka [libobjc2](https://github.com/gnustep/libobjc2)). Most things are working now, except for interoperability with C++ exception handling in Objective-C++.

In order to work with different C++ runtimes, libobjc2 probes the C++ exception structure layout at runtime. @davidchisnall, the libobjc2 maintainer, wrote the following about his attempts to get this working with MinGW (see https://github.com/gnustep/libobjc2/pull/190#issuecomment-812854070):

> There's something odd with MinGW's bridging of the SEH and DWARF EH models that is breaking the code that tries to figure out the layout of the C++ exception structure. I've pushed changes that let me pass all of the tests except those related to C++ exception interop.
> 
> It looks as if the __gxx_personality_v0 symbol isn't exported from the C++ runtime with MinGW, so we can't wrap it for Objective-C++ anyway. I don't see any way of getting C++ exception interop working with MinGW. If you know anyone on the MinGW project, perhaps they could help? [...]

> Thinking a bit more about it, the right strategy for MinGW may be to simply punt all exception handling to the C++ runtime, as Apple does.

Is there anyone here who could help shed some light on the above, or is there a better place for me to post this?

Using Objective-C in MinGW currently only works using GCC and its Objective-C runtime, which is lacking support for many more modern language features that libobjc2 provides. This is why MinGW support in libobjc2 has been a much requested feature, and I would appreciate any help to make this happen. Thanks!

**Comment by mati865** [comment]
Looking at `llvm-readobj --coff-exports /mingw32/bin/libstdc++-6.dll` output it seems properly exported:
```
Export {
  Ordinal: 6599
  Name: __gxx_personality_v0
  RVA: 0xEBAE0
}
```
I guess you are not looking for the right symbol, for 32-bit mingw-w64 it is `___gxx_personality_v0` (note there are 3 `_`) and for 64-bit mingw-w64 it is `__gxx_personality_seh0`.

**Comment by davidchisnall** [comment]
We are looking at the 64-bit version.  `__gxx_personality_seh0` is the SEH personality function, `__gxx_personality_v0` is the DWARF EH version.  As I understand it, MinGW uses a hybrid model where the compiler populates a DWARF LSDA but provides an SEH personality function that wraps the DWARF personality routine and translates the responses back.

The Objective-C runtime provides two implementations of exception handling:

 - For DWARF EH platforms, we provide a native EH model for Objective-C and will inject C++ EH ABI exceptions for Objective-C++, delegating to the C++ runtime's exception personality routine (we provide `std::type_info` subclasses representing Objective-C types, which allows the C++ runtime to generate the correct matches).  Objective-C stack frames have an LSDA that contains only Objective-C metadata, Objective-C++ stack frames have a standard C++ LSDA.  This requires that we can call `__gxx_personality_v0` from the Objective-C personality function when we are in an Objective-C++ frame, after we wrap the exception.
 - For Windows, we use the `__CxxFrameHandler3` personality function and throw exceptions that look like C++ exceptions.  Objective-C++ and Objective-C both just use MSVC-compatible unwind tables.

Neither of these approaches works with MinGW at present.  We cannot use the standard SEH model, because MinGW uses the Itanium C++ ABI and not the MSVC ABI and so we can't catch MSVC-style exceptions from a C++ stack frame.  We cannot use the DWARF model because libsupc++ (embedded in libstdc++.dll) does not export `__gxx_personality_v0` (on 64-bit builds, I believe things probably work on the non-SEH builds).

**Comment by mati865** [comment]
At least in LLVM's libc++ with mingw-w64 SEH you cannot call `__gxx_personality_v0` by design.
This function is `__gxx_personality_v0` on DWARF targets: https://github.com/llvm/llvm-project/blob/cfe9ccbddd98b55e49e46bb40877ece6a47a7625/libcxxabi/src/cxa_personality.cpp#L879-L944 but on mingw-w64 SEH it gets mangled as `_ZN10__cxxabiv1L21__gxx_personality_impEi14_Unwind_ActionyP17_Unwind_ExceptionP15_Unwind_Context`.
Instead `__gxx_personality_seh0` is exported: https://github.com/llvm/llvm-project/blob/cfe9ccbddd98b55e49e46bb40877ece6a47a7625/libcxxabi/src/cxa_personality.cpp#L946-L954

This code is compatible with GCC implementation so I think GCC's libstdc++ does it similar way.

I think you might have more luck asking on GCC or mingw-w64 mailing lists.
