### ISSUE TITLE
hmm python jupyter packages

### ISSUE THREAD

**Issue by revelator** [msys2/MINGW-packages#8362]
most of them seem broken ? jupyter nbconvert needs pycurl which needs a good deal of patching to build with our brand of python,
jupyter qtconsole needs pywin32 which has not been ported yet and even jupyter console has dependencies we do not have.

**Comment by peterbud** [comment]
Yes, they were working at the time when added to the repo, but as you pointed out they are unfortunately broken. Best case would be to remove them from the repo.

**Comment by revelator** [comment]
well atleast untill we have proper ports atleast :)

**Comment by revelator** [comment]
tcl nsf also seems to have some trouble atleast executing the nsf shell spews an error about not being able to load nsf2.3.0 which i suspect is a missing dll module atm it only contains a stub.

**Comment by yuyichao** [comment]
I get the mingw64 of jupyter qtconsole running with only packages from the repo.

1. The qtconsole package is missing some dependencies: qtpy, ipykernel
2. The win32api dependency can be worked around by setting `JUPYTER_ALLOW_INSECURE_WRITES=true`
3. `/mingw64/bin/jupyter-qtconsole.exe` together with many other similar ones are broken somehow (wrong format?) The python script `/mingw64/bin/jupyter-qtconsole` works though and can be run directly.
4. The ipykernel file stores the installation directory on the build machine, i.e. `D://a/....`, replacing it with the actual installation path makes it works.


Out of these, 1 is easily fixable. 2 can be recommended in post_install/post_upgrade, 3 is probably a build problem and can at least remove the .exe for qtconsole (not for others) to avoid confusion. 4 can probably be fixed with a post_install/post_upgrade in the ipykernel package.
Should I open separate issues for these?
