### ISSUE TITLE
Wrong default target in `mingw-w64-x86_64-llvm-11.0.0-11`

### ISSUE THREAD

**Issue by Il-Capitano** [msys2/MINGW-packages#8517]
The default target changed from previous builds of the package, I think starting from `11.0.0-10`, although I'm not 100% on this. Previously it was `x86_64-w64-windows-gnu`, now it's `x86_64-w64-mingw32`.
Running `/mingw64/bin/llc --version` yields:
```
LLVM (http://llvm.org/):
  LLVM version 11.0.0
  Optimized build.
  Default target: x86_64-w64-mingw32
  Host CPU: haswell
```
Getting the default target via `llvm::sys::getDefaultTargetTriple()` also results in `x86_64-w64-mingw32`.

The `mingw-w64-x86_64-clang-11.0.0-11` package doesn't seem to have this problem, running `/mingw64/bin/clang --version` yields:
```
clang version 11.0.0
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```

**Comment by Il-Capitano** [comment]
I said it's "wrong" because it's different from previous builds and it's different from what the `clang` package uses.
Compiling a simple hello world LLVM-IR file using `llc` and linking with `clang` doesn't work for example:
```
; main.ll
@.str = private unnamed_addr constant [14 x i8] c"Hello world!\0A\00", align 1

declare dso_local i32 @printf(i8* %0, ...)

define i32 @main() {
  %1 = call i32(i8*, ...) @printf(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @.str, i32 0, i32 0))
  ret i32 0
}
```
```
$ llc main.ll --filetype=obj -o main.o
$ clang main.o -o a.exe
main.o: in function `main':
main.ll:(.text+0x2): relocation truncated to fit: R_X86_64_32 against `.rodata.str1.1'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Il-Capitano** [comment]
Also note that explicitly specifying a target triple for `llc` works
```
$ llc main.ll --filetype=obj --mtriple=x86_64-w64-windows-gnu -o main.o
$ clang main.o -o a.exe
$ ./a
Hello world!
```

**Comment by mati865** [comment]
> @mati865 I set LLVM_HOST_TRIPLE to `${MINGW_CHOST}`, maybe that's the cause?  I'm not quite sure why `x86_64-w64-mingw32` is "wrong" though, it's what every other package uses

Yeah, that is the reason.
In older versions both types used to work.

**Comment by jeremyd2019** [comment]
Should it be `${CARCH}-w64-windows-gnu` then?  or is that going to hit the strange i386 vs i686 issue for 32-bit?

**Comment by mati865** [comment]
> 
> 
> Should it be `${CARCH}-w64-windows-gnu` then? or is that going to hit the strange i386 vs i686 issue for 32-bit? Actually I can't remember now if setting LLVM_HOST_TRIPLE explicitly is necessary or only for the cross compiling PKGBUILD from CLANG-packages and it came along for the ride.

I'd bet it's only necessary for cross compilation.
I think `i386` could cause an issue since on Linux different `iX86` architectures enable different features.

**Comment by mstorsjo** [comment]
Just for reference here; `<arch>-w64-mingw32` and `<arch>-w64-windows-gnu` are supposed to be equivalent in LLVM; the latter is the normalized form of the former. They're supposed to work identically everywhere. But apparently there's a gap, where the triple taken from the `-mtriple` option gets normalized, while the one from `sys::getDefaultTargetTriple()` isn't: https://github.com/llvm/llvm-project/blob/1db4dbba24dd36bd5a91ed58bd9d92dce2060c9f/llvm/tools/llc/llc.cpp#L494-L498

In all practical matters, this shouldn't make any difference, but at least in current LLVM this does lead to llc actually creating an ELF target. I'll try to dig in to whether it's the underlying libraries that are missing some normalization, or if llc should normalize both cases - as they're supposed to be equivalent.

I'm pointing this out, because I'd generally prefer using the `<arch>-w64-mingw32` form, because that one generally works better e.g. for cases where things try to find a sysroot in the form of `<bindir>/../<literal_triple>`. (There's a fallback in clang for such sysroot detection though, looking for both the literal triple and explicitly `<bindir>/../<arch>-w64-mingw32` too, but overall I think it might be safer for us to consistently use our preferred spelling, and then have llvm internally normalize things consistently.)
