### ISSUE TITLE
arm-none-eabi-gdb and avr-gdb: are they still necessary?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#8521]
I was fixing packages that failed to build on clang64, and noticed that gdb builds a 'multiarch' variant now.   This made me wonder if mingw-w64-arm-none-eabi-gdb is still necessary, or if it could be removed?  It is an older version than gdb now.

/cc @fauxpark

**Comment by jeremyd2019** [comment]
#9563 - seems like having gdb-multiarch as a split package from the "one true" gdb source package makes it less likely to bitrot

**Comment by selectstriker2** [comment]
The only issue I have with the change in #19259 is that gdb-multiarch is marked as conflicting with arm-none-eabi-gdb and avr-gdb, when it doesn't actual conflict with those packages, it can just replace them.

This causes an issue for my environment because I need to maintain a specific version of avr-gdb (that I built) in parallel with gdb-multiarch (using for arm-none-eabi-gdb)

**Comment by MehdiChinoune** [comment]
Could you explain why couldn't you use gdb-multiarch for avr?

**Comment by selectstriker2** [comment]
I have a requirement to maintain a specific toolchain environment (in this cases avr-gcc 11.3.0-1, avr-gdb 11.2-1) for compiling and verification of a product.

**Comment by MehdiChinoune** [comment]
You could install them in a different location.
like the normal one in C:\msys64 and the one used for that product in C:\msys64_avt

**Comment by selectstriker2** [comment]
But that shouldn't be necessary, because the packages don't actually conflict with each other.

If I have to I'll just patch the gdb-multiarch PKGBUILD file to remove the "conflicts" in `package_gdb-multiarch()` and build the gdb-multiarch package myself
