### ISSUE TITLE
About the TeXLive banner

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#8693]
From the PKGBUILD I see you use `Built by MSYS2 project` but _only_ MinGW64/32 packages exist, so the banner should reflect this.  Often on other systems the banner is just `TeX Live 2021` and so on...

**Comment by oscarfv** [comment]
What's the problem, exactly? `Built by MSYS2 project` is a correct statement, isn't it?

What other packages did you expect? Please note that MSYS2 (POSIX) packages are usually introduced for building MinGW-XX packages or because there is no native port, there is no reason to provide a  MSYS2 package when the MinGW-XX ones work fine.

**Comment by naveen521kk** [comment]
Again, what's wrong with `Built by MSYS2 project`?

> Often on other systems the banner is just TeX Live 2021 and so on...

Arch set it to `Archlinux`, native TeX Live win32 set it to `W32TeX`, it's meant to set a custom name by distro packagers.

>  but only MinGW64/32 packages exist, so the banner should reflect this.

why? it will be available on ucrt and clang once it gets Perl.
