### ISSUE TITLE
`std::call_once` from libstdc++ always segfaults on Clang 12 - patch included

### ISSUE THREAD

**Issue by HolyBlackCat** [msys2/MINGW-packages#8706]
I can reproduce on both MSYS2 Clang, and the official Windows and Ubuntu binaries.

It's a regression from Clang 11, where it used to work. It seems Clang 12 doesn't like namespace-scope TLS on MinGW.

A minimal code that crashes:
```cpp
#include <iostream>
#include <mutex>

int main()
{
    std::once_flag flag;
    std::call_once(flag, []{std::cout << "Once!\n";});
}
```

A proper fix would be on Clang's side, but as a workaround we can patch libstdc++ (`/mingw64/include/c++/10.3.0/mutex`).
```cpp
@@ -691,8 +691,8 @@ _GLIBCXX_BEGIN_NAMESPACE_VERSION

   /// @cond undocumented
 #ifdef _GLIBCXX_HAVE_TLS
-  extern __thread void* __once_callable;
-  extern __thread void (*__once_call)();
+  inline void *&__once_callable_get() {static __thread void *__ret; return __ret;}
+  inline void (*&__once_call_get())() {static __thread void (*__ret)(); return __ret;}
 #else
   extern function<void()> __once_functor;

@@ -703,7 +703,7 @@ _GLIBCXX_BEGIN_NAMESPACE_VERSION
   __get_once_mutex();
 #endif

-  extern "C" void __once_proxy(void);
+  extern "C" inline void __once_proxy_inline(void) {__once_call_get()();}
   /// @endcond

   /// Invoke a callable and synchronize with other calls using the same flag
@@ -718,15 +718,15 @@ _GLIBCXX_BEGIN_NAMESPACE_VERSION
            std::forward<_Args>(__args)...);
       };
 #ifdef _GLIBCXX_HAVE_TLS
-      __once_callable = std::__addressof(__callable); // NOLINT: PR 82481
-      __once_call = []{ (*(decltype(__callable)*)__once_callable)(); };
+      __once_callable_get() = std::__addressof(__callable); // NOLINT: PR 82481
+      __once_call_get() = []{ (*(decltype(__callable)*)__once_callable_get())(); };
 #else
       unique_lock<mutex> __functor_lock(__get_once_mutex());
       __once_functor = __callable;
       __set_once_functor_lock_ptr(&__functor_lock);
 #endif

-      int __e = __gthread_once(&__once._M_once, &__once_proxy);
+      int __e = __gthread_once(&__once._M_once, &__once_proxy_inline);

 #ifndef _GLIBCXX_HAVE_TLS
       if (__functor_lock)
```

**Comment by HolyBlackCat** [comment]
Reported a [bug to Clang](https://bugs.llvm.org/show_bug.cgi?id=50146) 3 weeks ago, got zero reaction. :/

**Comment by jeremyd2019** [comment]
yeah, thread support for Windows in libstdc++ is ... problematic

**Comment by HolyBlackCat** [comment]
@jeremyd2019 It's Clang's problem. It used to work in Clang 11, then broke in Clang 12. So it's probably them who should fix it.

**Comment by mstorsjo** [comment]
I think I've seen something similar before; try if using `-femulated-tls` with Clang helps.

Clang defaults to using the platform's native TLS support, while GCC doesn't support that - which technically is an ABI difference between Clang and GCC. It's normally not an issue as long as all accesses to TLS variables are done with the same ABI, but in this case, the variable is defined in libstdc++ and accessed from code built with Clang. Given the kind workaround, I think it might be the root cause.

I remeber hearing about this issue long earlier, so I'm not sure if it's strictly a regression from Clang 11 to 12 - my guess is that it just happened to seem like it works with Clang 11, even if the same root cause was there.

As for the suggested workaround patch - I'm not sure if that's safe, as I presume there's some reason for things using one single global TLS variable, while this now ends up a separate TLS variable for each object file accessing it. But I'm not familiar with that part of the libstdc++ std::call_once implementation to comment on what effect it has.

**Comment by HolyBlackCat** [comment]
@mstorsjo That's already with `-femulated-tls`, without it I get linkers errors (regardless of Clang version).

Different object files should get the same TLS with this patch. Different dlls might get different ones though.

**Comment by mstorsjo** [comment]
> @mstorsjo That's already with `-femulated-tls`, without it I get linkers errors (regardless of Clang version).

Oh, ok, that explains that bit.

> Different object files should get the same TLS with this patch. Different dlls might get different ones though.

Hmm, maybe yeah - static variables in an inline function is an odd thing...


In any case, I can try to take a look at bisecting what changed between Clang 11 and 12 and where this broke, but it's going to take a while.

**Comment by HolyBlackCat** [comment]
@mstorsjo This might be helpful: https://bugs.llvm.org/show_bug.cgi?id=48030

It looks like a similar issue, but I'm not completely sure. The author thinks that his issue was caused by `00223827a952f66e7426c9881a2a4229e59bb019 - Improve code generation for thread_local variables`.

**Comment by mstorsjo** [comment]
A patch for fixing this issue is posted at https://reviews.llvm.org/D102970.

**Comment by mstorsjo** [comment]
The fix commit was now pushed as https://github.com/llvm/llvm-project/commit/0e4cf807aeaf54a10e02176498a7df13ac722b37.

**Comment by shithappens2016** [comment]
@mstorsjo  @HolyBlackCat
By the way, with
```
clang++ -fuse-ld=lld test.cc -flto=thin
```
you will get

```
lld-link: error: undefined symbol: std::__once_callable
>>> referenced by test.cc
>>>               test-39c3a4.o

lld-link: error: undefined symbol: std::__once_call
>>> referenced by test.cc
>>>               test-39c3a4.o
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by HolyBlackCat** [comment]
@shithappens2016 It seems to be caused by trying to compile and link in one step. If you do it separately, it should work.

**Comment by mstorsjo** [comment]
Just for future reference, for cross referencing related issues:

The mentioned fix, in https://github.com/llvm/llvm-project/commit/0e4cf807aeaf54a10e02176498a7df13ac722b37 (since Clang 13.0), was enough to fix the issue as long as `-f[no-]emulated-tls` was specified explicitly - but if enabled implicitly, it didn't work as expected.

A fix for that was sought out in https://github.com/msys2/MINGW-packages/pull/12550#issuecomment-1228506687, applied in msys2 in https://github.com/msys2/MINGW-packages/pull/12852 (for the msys2 Clang 15.0 builds). The fix was later upstreamed in a slightly different form in https://github.com/llvm/llvm-project/commit/fbfe1db4a95a73ed6a0767db0ab7d449fc03405e for Clang 16.0, so the backported fix in msys2 was changed in https://github.com/msys2/MINGW-packages/pull/13253/commits/b9d83ff84983c8ff1f3f3a11d9d9b3fc06dbc573 for the msys2 provided Clang 15.0.
