### ISSUE TITLE
clang: creating 'depends' with -MMD -MF uses backslashes in paths

### ISSUE THREAD

**Issue by waltje** [msys2/MINGW-packages#9614]
When generating dependencies, clang will use backslashes in the generated
pathnames:

`pc.o: pc.c emu.h plat.h log.h version.h config.h timer.h cpu\cpu.h \
  cpu\x86.h cpu\codegen.h io.h mem.h rom.h device.h nvr.h misc\random.h \
  machines\machine.h devices\system\clk.h devices\system\dma.h \`

which of course won't work, if at all because they are not escaped :P 

These should be forward slashes.

**Comment by jeremyd2019** [comment]
This was already "fixed": https://github.com/msys2/MINGW-packages/pull/9414

But, the comments in the code are pretty clear that unescaped backslashes *would* work in that case, and the *fix* was only for autotools to recognize the format of the dependency files, because it grepped for forward slashes.
