### ISSUE TITLE
How do I get MINGW packages to use Linux paths instead of Windows paths?

### ISSUE THREAD

**Issue by bbholty1** [msys2/MINGW-packages#9861]
--> /mingw64/bin/diff
diff.exe: missing operand after 'C:\Users\1000278796\Documents\msys64\mingw64\bin\diff.exe'
diff.exe: Try '**C:\Users\1000278796\Documents\msys64\mingw64\bin\diff.exe** --help' for more information.
--> /usr/bin/diff
/usr/bin/diff: missing operand after '/usr/bin/diff'
/usr/bin/diff: Try '**/usr/bin/diff** --help' for more information.
 
I have been systematically removing Mingw64 packages (cmake, sed, grep, diff, ...) because they aren't compatible with the other tools I use.

Is there a way to force Mingw64 packages to use Linux paths?
I feel I'm missing something simple here. 😄 

Thanks!

**Comment by oscarfv** [comment]
MinGW packages are native Win32 applications, while MSYS2 packages run on top of a POSIX emulation layer. MinGW applications don't understand POSIX paths for the same reason Linux applications don't understand Windows paths.

When you invoke a MinGW (or any other native Win32 application) from a MSYS2 shell, MSYS2 takes care of translating POSIX paths on the command line and the environment to Win32 paths, that's why you can type this in the shell:

$ /mingw64/bin/emacs /path/to/file.c

and it will work because emacs is actually invoked with something like `c:\path\to\file.c`.

If this answers your question, please close this issue. Thanks.

**Comment by bbholty1** [comment]
Thanks for the explanation!
