### ISSUE TITLE
error messages after installing/upgrading/removing adwaita-icon-theme

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MINGW-packages#9952]
Installing:
```
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_8z2X6T/.INSTALL; post_install 41.0-1 ) failed to execute correctly
```
Upgrading (Reinstalling)
```
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_F55wzp/.INSTALL; post_upgrade 41.0-1 41.0-1 ) failed to execute correctly
```
Removing
```
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_7wHFCX/.INSTALL; post_remove 41.0-1 ) failed to execute correctly
```

something in the post_install script?

**Comment by h-c-mueller** [comment]
Same happend to me. 
Installing e.g. `mingw-w64-x86_64-gtk-update-icon-cache` before resolved the problem. 
So the root cause seems a missing dependency in `PKGBUILD` to `"${MINGW_PACKAGE_PREFIX}-gtk-update-icon-cache"`.
I assume `PKGBUILD` should contain:
```
depends=("${MINGW_PACKAGE_PREFIX}-hicolor-icon-theme"
         "${MINGW_PACKAGE_PREFIX}-librsvg"
         "${MINGW_PACKAGE_PREFIX}-gtk-update-icon-cache")
```

**Comment by MehdiChinoune** [comment]
> Same happend to me. Installing e.g. `mingw-w64-x86_64-gtk-update-icon-cache` before resolved the problem. So the root cause seems a missing dependency in `PKGBUILD` to `"${MINGW_PACKAGE_PREFIX}-gtk-update-icon-cache"`. I assume `PKGBUILD` should contain:
> 
> ```
> depends=("${MINGW_PACKAGE_PREFIX}-hicolor-icon-theme"
>          "${MINGW_PACKAGE_PREFIX}-librsvg"
>          "${MINGW_PACKAGE_PREFIX}-gtk-update-icon-cache")
> ```

I don't think so, the install script check the existence of gtk-update-icon-cache before executing.

**Comment by h-c-mueller** [comment]
You are right. I missed this.

**Comment by RadSuit** [comment]
I guess reopening this issue would be better than reiterating on the same issue with a new issue entry. I tried installing build dependencies for GIMP plugin development for clang. This was the faulting package for me when initially installing it. The error I got was:
`error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_bbf87v/.INSTALL; post_install 41.0-1 ) failed to execute correctly`

However, it doesn't reappear upon reinstalling it. So I guess this issue isn't as critical as OP's issue. It just caught my attention that it threw out an error when installing it alongside the other packages for GIMP. Also, I don't want to uninstall and install it again because it might break a package that depends on it. So I haven't tested it again from a clean install.
